<?php

declare(strict_types=1);
/**
 * This File is part of JTL-Software
 *
 * User: generated by Junie
 * Date: 2025/09/05
 */

namespace JTL\SCX\Lib\Channel\Event\Seller;

use JTL\SCX\Lib\Channel\Client\Model\SellerEventTest;
use PHPUnit\Framework\TestCase;

/**
 * @covers \JTL\SCX\Lib\Channel\Event\Seller\SystemTestEvent
 */
class SystemTestEventTest extends TestCase
{
    /**
     * @test
     */
    public function it_exposes_underlying_api_event_model()
    {
        $apiEventModel = $this->createStub(SellerEventTest::class);
        $event = new SystemTestEvent('id', 'version', new \DateTimeImmutable(), $apiEventModel);
        $this->assertSame($apiEventModel, $event->getEvent());
    }
}
