<?php
/**
 * AddressTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * AddressTest Class Doc Comment
 *
 * @category    Class
 * @description Address
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\Address
 */
class AddressTest extends AbstractApiModelTest
{
    /**
     * Test allowed values for gender
     * @test
     */
    public function it_has_correct_allowed_values_for_gender(): void
    {
        $allowed = [
            'male','female','diverse',
        ];

        $sut = new Address();
        $this->assertMethodExists($sut, 'getGenderAllowableValues');
        $this->assertEquals($allowed, $sut->getGenderAllowableValues());
    }
    /**
     * @return array
     * @dataProvider
     */
    public function expectedInterface(): array
    {
        return [
            'assert property firstName' => [
                'firstName',
                'string',
                'getFirstName',
                'setFirstName',
                true
            ],
            'assert property lastName' => [
                'lastName',
                'string',
                'getLastName',
                'setLastName',
                false
            ],
            'assert property gender' => [
                'gender',
                'string',
                'getGender',
                'setGender',
                true
            ],
            'assert property companyName' => [
                'companyName',
                'string',
                'getCompanyName',
                'setCompanyName',
                true
            ],
            'assert property street' => [
                'street',
                'string',
                'getStreet',
                'setStreet',
                false
            ],
            'assert property houseNumber' => [
                'houseNumber',
                'string',
                'getHouseNumber',
                'setHouseNumber',
                true
            ],
            'assert property addition' => [
                'addition',
                'string',
                'getAddition',
                'setAddition',
                true
            ],
            'assert property postcode' => [
                'postcode',
                'string',
                'getPostcode',
                'setPostcode',
                true
            ],
            'assert property city' => [
                'city',
                'string',
                'getCity',
                'setCity',
                false
            ],
            'assert property phone' => [
                'phone',
                'string',
                'getPhone',
                'setPhone',
                true
            ],
            'assert property country' => [
                'country',
                'string',
                'getCountry',
                'setCountry',
                false
            ],
            'assert property state' => [
                'state',
                'string',
                'getState',
                'setState',
                true
            ],
        ];
    }

    /**
     * @test
     * @dataProvider expectedInterface
     */
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter, bool $isNullable): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new Address([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);

        if ($isNullable) {
            $sut = new Address([$property => null]);
            $this->assertNull($sut->$expectedGetter());

            $sut->$expectedSetter(null);
            $this->assertNull($sut->$expectedGetter());
        }
    }

}
