<?php
/**
 * AttributeTypeTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * AttributeTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Attribute type describes which kind of data is expected for a particular attribute.  * Type **smalltext** is considered plain text and may not exceed more than 255 characters. * Type **text** is considered plain text and may not exceed a maximum length more than 50.000 characters. * Type **htmltext** may be used for text where HTML Markup is allowed. The maximum length should not exceed more than 50.000 characters. * Type **date** must follow [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard with Timezone. * Type **enum** may provide a set of allowed choices via the values property * Type **image** a attribute with an existing remote File uploaded using &#x60;POST /v1/seller/offer/file&#x60; * Type **document** a attribute with an existing remote File uploaded using &#x60;POST /v1/seller/offer/file&#x60; * Type **url** must match a URL Schema * Type **label** can be used as help text. Requires description to be set
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\AttributeType
 */
class AttributeTypeTest extends AbstractApiModelTest
{
    /**
     * Test Enum Value "SMALLTEXT"
     * @test
     */
    public function is_a_const_SMALLTEXT(): void
    {
        self::assertEquals('smalltext', AttributeType::SMALLTEXT);
        $sut = new AttributeType('smalltext');
        self::assertEquals('smalltext', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "SMALLTEXT"
     * @test
     */
    public function it_can_be_constructed_forSMALLTEXT(): void
    {
        $sut = AttributeType::SMALLTEXT();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "HTMLTEXT"
     * @test
     */
    public function is_a_const_HTMLTEXT(): void
    {
        self::assertEquals('htmltext', AttributeType::HTMLTEXT);
        $sut = new AttributeType('htmltext');
        self::assertEquals('htmltext', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "HTMLTEXT"
     * @test
     */
    public function it_can_be_constructed_forHTMLTEXT(): void
    {
        $sut = AttributeType::HTMLTEXT();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "TEXT"
     * @test
     */
    public function is_a_const_TEXT(): void
    {
        self::assertEquals('text', AttributeType::TEXT);
        $sut = new AttributeType('text');
        self::assertEquals('text', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "TEXT"
     * @test
     */
    public function it_can_be_constructed_forTEXT(): void
    {
        $sut = AttributeType::TEXT();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "INTEGER"
     * @test
     */
    public function is_a_const_INTEGER(): void
    {
        self::assertEquals('integer', AttributeType::INTEGER);
        $sut = new AttributeType('integer');
        self::assertEquals('integer', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "INTEGER"
     * @test
     */
    public function it_can_be_constructed_forINTEGER(): void
    {
        $sut = AttributeType::INTEGER();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "DECIMAL"
     * @test
     */
    public function is_a_const_DECIMAL(): void
    {
        self::assertEquals('decimal', AttributeType::DECIMAL);
        $sut = new AttributeType('decimal');
        self::assertEquals('decimal', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "DECIMAL"
     * @test
     */
    public function it_can_be_constructed_forDECIMAL(): void
    {
        $sut = AttributeType::DECIMAL();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "ENUM"
     * @test
     */
    public function is_a_const_ENUM(): void
    {
        self::assertEquals('enum', AttributeType::ENUM);
        $sut = new AttributeType('enum');
        self::assertEquals('enum', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "ENUM"
     * @test
     */
    public function it_can_be_constructed_forENUM(): void
    {
        $sut = AttributeType::ENUM();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "DATE"
     * @test
     */
    public function is_a_const_DATE(): void
    {
        self::assertEquals('date', AttributeType::DATE);
        $sut = new AttributeType('date');
        self::assertEquals('date', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "DATE"
     * @test
     */
    public function it_can_be_constructed_forDATE(): void
    {
        $sut = AttributeType::DATE();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "BOOLEAN"
     * @test
     */
    public function is_a_const_BOOLEAN(): void
    {
        self::assertEquals('boolean', AttributeType::BOOLEAN);
        $sut = new AttributeType('boolean');
        self::assertEquals('boolean', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "BOOLEAN"
     * @test
     */
    public function it_can_be_constructed_forBOOLEAN(): void
    {
        $sut = AttributeType::BOOLEAN();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "IMAGE"
     * @test
     */
    public function is_a_const_IMAGE(): void
    {
        self::assertEquals('image', AttributeType::IMAGE);
        $sut = new AttributeType('image');
        self::assertEquals('image', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "IMAGE"
     * @test
     */
    public function it_can_be_constructed_forIMAGE(): void
    {
        $sut = AttributeType::IMAGE();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "DOCUMENT"
     * @test
     */
    public function is_a_const_DOCUMENT(): void
    {
        self::assertEquals('document', AttributeType::DOCUMENT);
        $sut = new AttributeType('document');
        self::assertEquals('document', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "DOCUMENT"
     * @test
     */
    public function it_can_be_constructed_forDOCUMENT(): void
    {
        $sut = AttributeType::DOCUMENT();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "URL"
     * @test
     */
    public function is_a_const_URL(): void
    {
        self::assertEquals('url', AttributeType::URL);
        $sut = new AttributeType('url');
        self::assertEquals('url', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "URL"
     * @test
     */
    public function it_can_be_constructed_forURL(): void
    {
        $sut = AttributeType::URL();
        self::assertInstanceOf(AttributeType::class, $sut);
    }
    /**
     * Test Enum Value "LABEL"
     * @test
     */
    public function is_a_const_LABEL(): void
    {
        self::assertEquals('label', AttributeType::LABEL);
        $sut = new AttributeType('label');
        self::assertEquals('label', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "LABEL"
     * @test
     */
    public function it_can_be_constructed_forLABEL(): void
    {
        $sut = AttributeType::LABEL();
        self::assertInstanceOf(AttributeType::class, $sut);
    }

    /**
     * Test allowed values from Enum
     * @test
     */
    public function it_has_correct_set_of_allowed_values(): void
    {
        $allowed = [
            AttributeType::SMALLTEXT,
            AttributeType::HTMLTEXT,
            AttributeType::TEXT,
            AttributeType::INTEGER,
            AttributeType::DECIMAL,
            AttributeType::ENUM,
            AttributeType::DATE,
            AttributeType::BOOLEAN,
            AttributeType::IMAGE,
            AttributeType::DOCUMENT,
            AttributeType::URL,
            AttributeType::LABEL,
        ];
        self::assertEquals($allowed, AttributeType::getAllowableEnumValues());
    }

}
