<?php
/**
 * AttributeTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * AttributeTest Class Doc Comment
 *
 * @category    Class
 * @description Attribute
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\Attribute
 */
class AttributeTest extends AbstractApiModelTest
{
    /**
     * Test allowed values for type
     * @test
     */
    public function it_has_correct_allowed_values_for_type(): void
    {
        $allowed = [
            'smalltext','htmltext','text','integer','decimal','enum','date','boolean','image','document','url','label',
        ];

        $sut = new Attribute();
        $this->assertMethodExists($sut, 'getTypeAllowableValues');
        $this->assertEquals($allowed, $sut->getTypeAllowableValues());
    }
    /**
     * @return array
     * @dataProvider
     */
    public function expectedInterface(): array
    {
        return [
            'assert property attributeId' => [
                'attributeId',
                'string',
                'getAttributeId',
                'setAttributeId',
                false
            ],
            'assert property displayName' => [
                'displayName',
                'string',
                'getDisplayName',
                'setDisplayName',
                false
            ],
            'assert property isMultipleAllowed' => [
                'isMultipleAllowed',
                'bool',
                'getIsMultipleAllowed',
                'setIsMultipleAllowed',
                false
            ],
            'assert property type' => [
                'type',
                'string',
                'getType',
                'setType',
                false
            ],
            'assert property values' => [
                'values',
                '\JTL\SCX\Lib\Channel\Client\Model\AllowedValue[]',
                'getValues',
                'setValues',
                true
            ],
            'assert property attributeValueValidation' => [
                'attributeValueValidation',
                'string',
                'getAttributeValueValidation',
                'setAttributeValueValidation',
                true
            ],
            'assert property conditionalMandatoryBy' => [
                'conditionalMandatoryBy',
                '\JTL\SCX\Lib\Channel\Client\Model\AttributeConditionalMandatoryByInner[]',
                'getConditionalMandatoryBy',
                'setConditionalMandatoryBy',
                true
            ],
            'assert property conditionalOptionalBy' => [
                'conditionalOptionalBy',
                '\JTL\SCX\Lib\Channel\Client\Model\AttributeConditionalMandatoryByInner[]',
                'getConditionalOptionalBy',
                'setConditionalOptionalBy',
                true
            ],
            'assert property required' => [
                'required',
                'bool',
                'getRequired',
                'setRequired',
                false
            ],
            'assert property recommended' => [
                'recommended',
                'bool',
                'getRecommended',
                'setRecommended',
                false
            ],
            'assert property section' => [
                'section',
                'string',
                'getSection',
                'setSection',
                true
            ],
            'assert property sectionPosition' => [
                'sectionPosition',
                'int',
                'getSectionPosition',
                'setSectionPosition',
                false
            ],
            'assert property isRepeatableSubSection' => [
                'isRepeatableSubSection',
                'bool',
                'getIsRepeatableSubSection',
                'setIsRepeatableSubSection',
                false
            ],
            'assert property subSection' => [
                'subSection',
                'string',
                'getSubSection',
                'setSubSection',
                true
            ],
            'assert property subSectionPosition' => [
                'subSectionPosition',
                'int',
                'getSubSectionPosition',
                'setSubSectionPosition',
                false
            ],
            'assert property description' => [
                'description',
                'string',
                'getDescription',
                'setDescription',
                true
            ],
            'assert property isVariationDimension' => [
                'isVariationDimension',
                'bool',
                'getIsVariationDimension',
                'setIsVariationDimension',
                true
            ],
        ];
    }

    /**
     * @test
     * @dataProvider expectedInterface
     */
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter, bool $isNullable): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new Attribute([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);

        if ($isNullable) {
            $sut = new Attribute([$property => null]);
            $this->assertNull($sut->$expectedGetter());

            $sut->$expectedSetter(null);
            $this->assertNull($sut->$expectedGetter());
        }
    }

}
