<?php
/**
 * InvoiceMetaDataTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * InvoiceMetaDataTest Class Doc Comment
 *
 * @category    Class
 * @description InvoiceMetaData
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\InvoiceMetaData
 */
class InvoiceMetaDataTest extends AbstractApiModelTest
{
    /**
     * Test allowed values for taxAddressRole
     * @test
     */
    public function it_has_correct_allowed_values_for_taxAddressRole(): void
    {
        $allowed = [
            'shipFrom','shipTo',
        ];

        $sut = new InvoiceMetaData();
        $this->assertMethodExists($sut, 'getTaxAddressRoleAllowableValues');
        $this->assertEquals($allowed, $sut->getTaxAddressRoleAllowableValues());
    }
    /**
     * @return array
     * @dataProvider
     */
    public function expectedInterface(): array
    {
        return [
            'assert property type' => [
                'type',
                '\JTL\SCX\Lib\Channel\Client\Model\InvoiceDocumentType',
                'getType',
                'setType',
                false
            ],
            'assert property sellerId' => [
                'sellerId',
                'string',
                'getSellerId',
                'setSellerId',
                false
            ],
            'assert property orderId' => [
                'orderId',
                'string',
                'getOrderId',
                'setOrderId',
                false
            ],
            'assert property invoiceNumber' => [
                'invoiceNumber',
                'string',
                'getInvoiceNumber',
                'setInvoiceNumber',
                false
            ],
            'assert property originalInvoiceNumber' => [
                'originalInvoiceNumber',
                'string',
                'getOriginalInvoiceNumber',
                'setOriginalInvoiceNumber',
                true
            ],
            'assert property transactionDate' => [
                'transactionDate',
                '\DateTime',
                'getTransactionDate',
                'setTransactionDate',
                false
            ],
            'assert property taxCalculationDate' => [
                'taxCalculationDate',
                '\DateTime',
                'getTaxCalculationDate',
                'setTaxCalculationDate',
                false
            ],
            'assert property transactionDetails' => [
                'transactionDetails',
                'string',
                'getTransactionDetails',
                'setTransactionDetails',
                true
            ],
            'assert property shipmentDate' => [
                'shipmentDate',
                '\DateTime',
                'getShipmentDate',
                'setShipmentDate',
                true
            ],
            'assert property taxAddressRole' => [
                'taxAddressRole',
                'string',
                'getTaxAddressRole',
                'setTaxAddressRole',
                true
            ],
            'assert property exportOutsideEu' => [
                'exportOutsideEu',
                'bool',
                'getExportOutsideEu',
                'setExportOutsideEu',
                true
            ],
            'assert property currency' => [
                'currency',
                'string',
                'getCurrency',
                'setCurrency',
                false
            ],
            'assert property billingAddress' => [
                'billingAddress',
                '\JTL\SCX\Lib\Channel\Client\Model\Address',
                'getBillingAddress',
                'setBillingAddress',
                false
            ],
            'assert property sellerVatNumber' => [
                'sellerVatNumber',
                'string',
                'getSellerVatNumber',
                'setSellerVatNumber',
                true
            ],
            'assert property buyerVatNumber' => [
                'buyerVatNumber',
                'string',
                'getBuyerVatNumber',
                'setBuyerVatNumber',
                true
            ],
            'assert property orderList' => [
                'orderList',
                '\JTL\SCX\Lib\Channel\Client\Model\OrderInvoice[]',
                'getOrderList',
                'setOrderList',
                true
            ],
        ];
    }

    /**
     * @test
     * @dataProvider expectedInterface
     */
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter, bool $isNullable): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new InvoiceMetaData([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);

        if ($isNullable) {
            $sut = new InvoiceMetaData([$property => null]);
            $this->assertNull($sut->$expectedGetter());

            $sut->$expectedSetter(null);
            $this->assertNull($sut->$expectedGetter());
        }
    }

}
