<?php
/**
 * MarketplaceChannelsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use JTL\SCX\Lib\Channel\Client\AbstractApiModelTestCase;

/**
 * MarketplaceChannelsTest Class Doc Comment
 *
 * @category    Class
 * @description Only set for Platform Channel. Contains all Marketplace Channels as full channel objects that have been assigned to the platform.
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
#[CoversClass(\JTL\SCX\Lib\Channel\Client\Model\MarketplaceChannels::class)]
class MarketplaceChannelsTest extends AbstractApiModelTestCase
{
    #[Test]
    public function it_has_no_properties(): void
    {
        self::assertSame([], MarketplaceChannels::openAPITypes(), 'The generated model declares no properties');
        self::assertInstanceOf(ModelInterface::class, new MarketplaceChannels());
    }

}
