<?php
/**
 * OrderInvoiceTransactionItemTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * OrderInvoiceTransactionItemTest Class Doc Comment
 *
 * @category    Class
 * @description OrderInvoiceTransactionItem
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\OrderInvoiceTransactionItem
 */
class OrderInvoiceTransactionItemTest extends AbstractApiModelTest
{
    /**
     * Test allowed values for orderItemType
     * @test
     */
    public function it_has_correct_allowed_values_for_orderItemType(): void
    {
        $allowed = [
            'ITEM','SHIPPING','PAYMENT',
        ];

        $sut = new OrderInvoiceTransactionItem();
        $this->assertMethodExists($sut, 'getOrderItemTypeAllowableValues');
        $this->assertEquals($allowed, $sut->getOrderItemTypeAllowableValues());
    }
    /**
     * @return array
     * @dataProvider
     */
    public function expectedInterface(): array
    {
        return [
            'assert property orderItemId' => [
                'orderItemId',
                'string',
                'getOrderItemId',
                'setOrderItemId',
                false
            ],
            'assert property orderItemType' => [
                'orderItemType',
                'string',
                'getOrderItemType',
                'setOrderItemType',
                false
            ],
            'assert property sku' => [
                'sku',
                'string',
                'getSku',
                'setSku',
                true
            ],
            'assert property title' => [
                'title',
                'string',
                'getTitle',
                'setTitle',
                true
            ],
            'assert property quantity' => [
                'quantity',
                'float',
                'getQuantity',
                'setQuantity',
                false
            ],
            'assert property totalGrossPriceWithDiscounts' => [
                'totalGrossPriceWithDiscounts',
                'float',
                'getTotalGrossPriceWithDiscounts',
                'setTotalGrossPriceWithDiscounts',
                false
            ],
            'assert property totalNetPriceWithDiscounts' => [
                'totalNetPriceWithDiscounts',
                'float',
                'getTotalNetPriceWithDiscounts',
                'setTotalNetPriceWithDiscounts',
                false
            ],
            'assert property totalVatAmountWithDiscounts' => [
                'totalVatAmountWithDiscounts',
                'float',
                'getTotalVatAmountWithDiscounts',
                'setTotalVatAmountWithDiscounts',
                false
            ],
            'assert property vatRate' => [
                'vatRate',
                'float',
                'getVatRate',
                'setVatRate',
                false
            ],
            'assert property discounts' => [
                'discounts',
                '\JTL\SCX\Lib\Channel\Client\Model\OrderInvoiceTransactionItemDiscounts[]',
                'getDiscounts',
                'setDiscounts',
                true
            ],
        ];
    }

    /**
     * @test
     * @dataProvider expectedInterface
     */
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter, bool $isNullable): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new OrderInvoiceTransactionItem([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);

        if ($isNullable) {
            $sut = new OrderInvoiceTransactionItem([$property => null]);
            $this->assertNull($sut->$expectedGetter());

            $sut->$expectedSetter(null);
            $this->assertNull($sut->$expectedGetter());
        }
    }

}
