<?php
/**
 * OrderShippingShippedFromTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SCX Channel API
 *
 * SCX Channel API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use JTL\SCX\Lib\Channel\Client\AbstractApiModelTestCase;

/**
 * OrderShippingShippedFromTest Class Doc Comment
 *
 * @category    Class
 * @description The adress from where the shipment is sent.
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
#[CoversClass(\JTL\SCX\Lib\Channel\Client\Model\OrderShippingShippedFrom::class)]
class OrderShippingShippedFromTest extends AbstractApiModelTestCase
{
    /**
     * @return array
     */
    public static function expectedInterface(): array
    {
        return [
            'assert property City' => [
                'city',
                'string',
                'getCity',
                'setCity'
            ],
            'assert property Country' => [
                'country',
                'string',
                'getCountry',
                'setCountry'
            ],
            'assert property Postcode' => [
                'postcode',
                'string',
                'getPostcode',
                'setPostcode'
            ],
        ];
    }

    #[DataProvider('expectedInterface')]
    #[Test]
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new OrderShippingShippedFrom([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);
    }
}
