<?php
/**
 * OrderShippingReturnTrackingTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SCX Channel API
 *
 * SCX Channel API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use JTL\SCX\Lib\Channel\Client\AbstractApiModelTestCase;

/**
 * OrderShippingReturnTrackingTest Class Doc Comment
 *
 * @category    Class
 * @description The return tracking number and carrier for the return process. Each orderItemId may have its own return tracking.
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
#[CoversClass(\JTL\SCX\Lib\Channel\Client\Model\OrderShippingReturnTracking::class)]
class OrderShippingReturnTrackingTest extends AbstractApiModelTestCase
{
    /**
     * @return array
     */
    public static function expectedInterface(): array
    {
        return [
            'assert property Carrier' => [
                'carrier',
                'string',
                'getCarrier',
                'setCarrier'
            ],
            'assert property TrackingNumber' => [
                'trackingNumber',
                'string',
                'getTrackingNumber',
                'setTrackingNumber'
            ],
        ];
    }

    #[DataProvider('expectedInterface')]
    #[Test]
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new OrderShippingReturnTracking([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);
    }
}
