<?php
/**
 * ReportTypeTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * ReportTypeTest Class Doc Comment
 *
 * @category    Class
 * @description ReportType
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\ReportType
 */
class ReportTypeTest extends AbstractApiModelTest
{
    /**
     * Test Enum Value "SELLER_INVENTORY"
     * @test
     */
    public function is_a_const_SELLER_INVENTORY(): void
    {
        self::assertEquals('SELLER_INVENTORY', ReportType::SELLER_INVENTORY);
        $sut = new ReportType('SELLER_INVENTORY');
        self::assertEquals('SELLER_INVENTORY', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "SELLER_INVENTORY"
     * @test
     */
    public function it_can_be_constructed_forSELLER_INVENTORY(): void
    {
        $sut = ReportType::SELLER_INVENTORY();
        self::assertInstanceOf(ReportType::class, $sut);
    }

    /**
     * Test allowed values from Enum
     * @test
     */
    public function it_has_correct_set_of_allowed_values(): void
    {
        $allowed = [
            ReportType::SELLER_INVENTORY,
        ];
        self::assertEquals($allowed, ReportType::getAllowableEnumValues());
    }

}
