<?php
/**
 * SalesChannelDataTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SCX Channel API
 *
 * SCX Channel API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * SalesChannelDataTest Class Doc Comment
 *
 * @category    Class
 * @description SalesChannelData
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\SalesChannelData
 */
class SalesChannelDataTest extends AbstractApiModelTest
{
    /**
     * Test allowed values for visibility
     * @test
     */
    public function it_has_correct_allowed_values_for_visibility(): void
    {
        $allowed = [
            'JTL','THIRDPARTY','ONBOARDING','RESTRICTED',
        ];

        $sut = new SalesChannelData();
        $this->assertMethodExists($sut, 'getVisibilityAllowableValues');
        $this->assertEquals($allowed, $sut->getVisibilityAllowableValues());
    }
    /**
     * Test allowed values for channelType
     * @test
     */
    public function it_has_correct_allowed_values_for_channelType(): void
    {
        $allowed = [
            'MARKETPLACE','OTHER',
        ];

        $sut = new SalesChannelData();
        $this->assertMethodExists($sut, 'getChannelTypeAllowableValues');
        $this->assertEquals($allowed, $sut->getChannelTypeAllowableValues());
    }
    /**
     * @return array
     * @dataProvider
     */
    public function expectedInterface(): array
    {
        return [
            'assert property channel' => [
                'channel',
                'string',
                'getChannel',
                'setChannel',
                false
            ],
            'assert property visibility' => [
                'visibility',
                'string',
                'getVisibility',
                'setVisibility',
                false
            ],
            'assert property group' => [
                'group',
                'string',
                'getGroup',
                'setGroup',
                true
            ],
            'assert property currency' => [
                'currency',
                'string',
                'getCurrency',
                'setCurrency',
                false
            ],
            'assert property marketplaceList' => [
                'marketplaceList',
                'string[]',
                'getMarketplaceList',
                'setMarketplaceList',
                false
            ],
            'assert property supportedLanguages' => [
                'supportedLanguages',
                'string[]',
                'getSupportedLanguages',
                'setSupportedLanguages',
                true
            ],
            'assert property displayName' => [
                'displayName',
                'string',
                'getDisplayName',
                'setDisplayName',
                false
            ],
            'assert property website' => [
                'website',
                'string',
                'getWebsite',
                'setWebsite',
                false
            ],
            'assert property pricing' => [
                'pricing',
                'string',
                'getPricing',
                'setPricing',
                true
            ],
            'assert property channelType' => [
                'channelType',
                'string',
                'getChannelType',
                'setChannelType',
                false
            ],
            'assert property supportContact' => [
                'supportContact',
                'string',
                'getSupportContact',
                'setSupportContact',
                false
            ],
            'assert property vendor' => [
                'vendor',
                'string',
                'getVendor',
                'setVendor',
                false
            ],
            'assert property signUpUrl' => [
                'signUpUrl',
                'string',
                'getSignUpUrl',
                'setSignUpUrl',
                false
            ],
            'assert property updateUrl' => [
                'updateUrl',
                'string',
                'getUpdateUrl',
                'setUpdateUrl',
                true
            ],
            'assert property logo' => [
                'logo',
                'string',
                'getLogo',
                'setLogo',
                true
            ],
            'assert property description' => [
                'description',
                'string',
                'getDescription',
                'setDescription',
                true
            ],
            'assert property appId' => [
                'appId',
                'string',
                'getAppId',
                'setAppId',
                true
            ]
        ];
    }

    /**
     * @test
     * @dataProvider expectedInterface
     */
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter, bool $isNullable): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new SalesChannelData([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);

        if ($isNullable) {
            $sut = new SalesChannelData([$property => null]);
            $this->assertNull($sut->$expectedGetter());

            $sut->$expectedSetter(null);
            $this->assertNull($sut->$expectedGetter());
        }
    }

    /**
     * @test
     */
    public function allowableValuesMatchEnum(): void
    {
        $instance = new SalesChannelData();
        $this->assertEquals([
            SalesChannelData::CHANNEL_TYPE_MARKETPLACE,
            SalesChannelData::CHANNEL_TYPE_OTHER,
        ], $instance->getChannelTypeAllowableValues());
    }
}
