<?php
/**
 * SellerEventOfferUpdateTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SCX Channel API
 *
 * SCX Channel API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * SellerEventOfferUpdateTest Class Doc Comment
 *
 * @category    Class
 * @description Update existing Offer.  If your current channel implementation process listing in asychronous manner it is recommended to call &#x60;/channel/offer/received&#x60; afterwards to mark wating Offers as in-progress. If a channel process an Offer directly you do not need to mark a Offer as &#x60;in-progress&#x60;. But it is important to mark an Offer as &#x60;successful&#x60; listed. If there are any errors during the listing process it is importand to mark a offer as &#x60;failed&#x60;.
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\SellerEventOfferUpdate
 */
class SellerEventOfferUpdateTest extends AbstractApiModelTest
{

    /**
     * @return array
     * @dataProvider
     */
    public function expectedInterface(): array
    {
        return [
            'assert property SellerId' => [
                'sellerId',
                'string',
                'getSellerId',
                'setSellerId',
                false
            ],
            'assert property OfferId' => [
                'offerId',
                'int',
                'getOfferId',
                'setOfferId',
                false
            ],
            'assert property ParentOfferId' => [
                'parentOfferId',
                'int',
                'getParentOfferId',
                'setParentOfferId',
                true
            ],
            'assert property ChannelOfferId' => [
                'channelOfferId',
                'string',
                'getChannelOfferId',
                'setChannelOfferId',
                true
            ],
            'assert property ChannelCategoryId' => [
                'channelCategoryId',
                'string',
                'getChannelCategoryId',
                'setChannelCategoryId',
                true
            ],
            'assert property Quantity' => [
                'quantity',
                'string',
                'getQuantity',
                'setQuantity',
                true
            ],
            'assert property TaxPercent' => [
                'taxPercent',
                'string',
                'getTaxPercent',
                'setTaxPercent',
                true
            ],
            'assert property PriceList' => [
                'priceList',
                '\JTL\SCX\Lib\Channel\Client\Model\PriceContainer[]',
                'getPriceList',
                'setPriceList',
                false
            ],
            'assert property Title' => [
                'title',
                'string',
                'getTitle',
                'setTitle',
                true
            ],
            'assert property SubTitle' => [
                'subTitle',
                'string',
                'getSubTitle',
                'setSubTitle',
                true
            ],
            'assert property Description' => [
                'description',
                'string',
                'getDescription',
                'setDescription',
                true
            ],
            'assert property MainPicture' => [
                'mainPicture',
                'string',
                'getMainPicture',
                'setMainPicture',
                true
            ],
            'assert property PictureList' => [
                'pictureList',
                'string[]',
                'getPictureList',
                'setPictureList',
                true
            ],
            'assert property ChannelAttributeList' => [
                'channelAttributeList',
                '\JTL\SCX\Lib\Channel\Client\Model\ChannelAttribute[]',
                'getChannelAttributeList',
                'setChannelAttributeList',
                true
            ],
            'assert property VariationList' => [
                'variationList',
                '\JTL\SCX\Lib\Channel\Client\Model\Variation[]',
                'getVariationList',
                'setVariationList',
                true
            ],
            'assert property Sku' => [
                'sku',
                'string',
                'getSku',
                'setSku',
                false
            ],
            'assert property Gtin' => [
                'gtin',
                'string',
                'getGtin',
                'setGtin',
                true
            ],
            'assert property Mpn' => [
                'mpn',
                'string',
                'getMpn',
                'setMpn',
                true
            ],
            'assert property Isbn' => [
                'isbn',
                'string',
                'getIsbn',
                'setIsbn',
                true
            ],
            'assert property Brand' => [
                'brand',
                'string',
                'getBrand',
                'setBrand',
                true
            ],
            'assert property Srp' => [
                'srp',
                '\JTL\SCX\Lib\Channel\Client\Model\Price',
                'getSrp',
                'setSrp',
                true
            ],
            'assert property ProductAttributeList' => [
                'productAttributeList',
                '\JTL\SCX\Lib\Channel\Client\Model\ProductAttribute[]',
                'getProductAttributeList',
                'setProductAttributeList',
                true
            ],
        ];
    }

    /**
     * @test
     * @dataProvider expectedInterface
     */
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter, bool $isNullable): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new SellerEventOfferUpdate([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);

        if ($isNullable) {
            $sut = new SellerEventOfferUpdate([$property => null]);
            $this->assertNull($sut->$expectedGetter());

            $sut->$expectedSetter(null);
            $this->assertNull($sut->$expectedGetter());
        }
    }
}
