<?php
/**
 * SellerEventOfferNewTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * SellerEventOfferNewTest Class Doc Comment
 *
 * @category    Class
 * @description List Offer on Channel.  If your current channel implementation process listing in asychronous manner it is recommended to call &#x60;/channel/offer/received&#x60; afterwards to mark wating Offers as in-progress. If a channel process an Offer directly you do not need to mark a Offer as &#x60;in-progress&#x60;. But it is important to mark an Offer as &#x60;successful&#x60; listed. If there are any errors during the listing process it is importand to mark a offer as &#x60;failed&#x60;.
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\SellerEventOfferNew
 */
class SellerEventOfferNewTest extends AbstractApiModelTest
{
    /**
     * @return array
     * @dataProvider
     */
    public function expectedInterface(): array
    {
        return [
            'assert property sellerId' => [
                'sellerId',
                'string',
                'getSellerId',
                'setSellerId',
                false
            ],
            'assert property offerId' => [
                'offerId',
                'int',
                'getOfferId',
                'setOfferId',
                false
            ],
            'assert property parentOfferId' => [
                'parentOfferId',
                'int',
                'getParentOfferId',
                'setParentOfferId',
                true
            ],
            'assert property channelOfferId' => [
                'channelOfferId',
                'string',
                'getChannelOfferId',
                'setChannelOfferId',
                true
            ],
            'assert property channelCategoryId' => [
                'channelCategoryId',
                'string',
                'getChannelCategoryId',
                'setChannelCategoryId',
                true
            ],
            'assert property quantity' => [
                'quantity',
                'string',
                'getQuantity',
                'setQuantity',
                true
            ],
            'assert property taxPercent' => [
                'taxPercent',
                'string',
                'getTaxPercent',
                'setTaxPercent',
                true
            ],
            'assert property priceList' => [
                'priceList',
                '\JTL\SCX\Lib\Channel\Client\Model\PriceContainer[]',
                'getPriceList',
                'setPriceList',
                false
            ],
            'assert property title' => [
                'title',
                'string',
                'getTitle',
                'setTitle',
                true
            ],
            'assert property subTitle' => [
                'subTitle',
                'string',
                'getSubTitle',
                'setSubTitle',
                true
            ],
            'assert property description' => [
                'description',
                'string',
                'getDescription',
                'setDescription',
                true
            ],
            'assert property mainPicture' => [
                'mainPicture',
                'string',
                'getMainPicture',
                'setMainPicture',
                true
            ],
            'assert property pictureList' => [
                'pictureList',
                'string[]',
                'getPictureList',
                'setPictureList',
                true
            ],
            'assert property channelAttributeList' => [
                'channelAttributeList',
                '\JTL\SCX\Lib\Channel\Client\Model\ChannelAttribute[]',
                'getChannelAttributeList',
                'setChannelAttributeList',
                true
            ],
            'assert property variationList' => [
                'variationList',
                '\JTL\SCX\Lib\Channel\Client\Model\Variation[]',
                'getVariationList',
                'setVariationList',
                true
            ],
            'assert property sku' => [
                'sku',
                'string',
                'getSku',
                'setSku',
                false
            ],
            'assert property gtin' => [
                'gtin',
                'string',
                'getGtin',
                'setGtin',
                true
            ],
            'assert property mpn' => [
                'mpn',
                'string',
                'getMpn',
                'setMpn',
                true
            ],
            'assert property isbn' => [
                'isbn',
                'string',
                'getIsbn',
                'setIsbn',
                true
            ],
            'assert property brand' => [
                'brand',
                'string',
                'getBrand',
                'setBrand',
                true
            ],
            'assert property srp' => [
                'srp',
                '\JTL\SCX\Lib\Channel\Client\Model\Price',
                'getSrp',
                'setSrp',
                true
            ],
            'assert property productAttributeList' => [
                'productAttributeList',
                '\JTL\SCX\Lib\Channel\Client\Model\ProductAttribute[]',
                'getProductAttributeList',
                'setProductAttributeList',
                true
            ],
        ];
    }

    /**
     * @test
     * @dataProvider expectedInterface
     */
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter, bool $isNullable): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new SellerEventOfferNew([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);

        if ($isNullable) {
            $sut = new SellerEventOfferNew([$property => null]);
            $this->assertNull($sut->$expectedGetter());

            $sut->$expectedSetter(null);
            $this->assertNull($sut->$expectedGetter());
        }
    }

}
