<?php
/**
 * SellerEventListEventListInnerEventTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * SellerEventListEventListInnerEventTest Class Doc Comment
 *
 * @category    Class
 * @description SellerEventListEventListInnerEvent
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\SellerEventListEventListInnerEvent
 */
class SellerEventListEventListInnerEventTest extends AbstractApiModelTest
{
    /**
     * Test allowed values for severity
     * @test
     */
    public function it_has_correct_allowed_values_for_severity(): void
    {
        $allowed = [
            'INFO','WARNING','ERROR',
        ];

        $sut = new SellerEventListEventListInnerEvent();
        $this->assertMethodExists($sut, 'getSeverityAllowableValues');
        $this->assertEquals($allowed, $sut->getSeverityAllowableValues());
    }
    /**
     * @return array
     * @dataProvider
     */
    public function expectedInterface(): array
    {
        return [
            'assert property sellerId' => [
                'sellerId',
                'string',
                'getSellerId',
                'setSellerId',
                false
            ],
            'assert property orderId' => [
                'orderId',
                'string',
                'getOrderId',
                'setOrderId',
                false
            ],
            'assert property shippingComplete' => [
                'shippingComplete',
                'bool',
                'getShippingComplete',
                'setShippingComplete',
                false
            ],
            'assert property shippingItems' => [
                'shippingItems',
                '\JTL\SCX\Lib\Channel\Client\Model\OrderShippingPosition[]',
                'getShippingItems',
                'setShippingItems',
                false
            ],
            'assert property paymentComplete' => [
                'paymentComplete',
                'bool',
                'getPaymentComplete',
                'setPaymentComplete',
                false
            ],
            'assert property paidAt' => [
                'paidAt',
                '\DateTime',
                'getPaidAt',
                'setPaidAt',
                false
            ],
            'assert property offerId' => [
                'offerId',
                'int',
                'getOfferId',
                'setOfferId',
                false
            ],
            'assert property channelOfferId' => [
                'channelOfferId',
                'string',
                'getChannelOfferId',
                'setChannelOfferId',
                true
            ],
            'assert property parentOfferId' => [
                'parentOfferId',
                'int',
                'getParentOfferId',
                'setParentOfferId',
                true
            ],
            'assert property channelCategoryId' => [
                'channelCategoryId',
                'string',
                'getChannelCategoryId',
                'setChannelCategoryId',
                true
            ],
            'assert property quantity' => [
                'quantity',
                'string',
                'getQuantity',
                'setQuantity',
                false
            ],
            'assert property taxPercent' => [
                'taxPercent',
                'string',
                'getTaxPercent',
                'setTaxPercent',
                true
            ],
            'assert property priceList' => [
                'priceList',
                '\JTL\SCX\Lib\Channel\Client\Model\PriceContainer[]',
                'getPriceList',
                'setPriceList',
                false
            ],
            'assert property title' => [
                'title',
                'string',
                'getTitle',
                'setTitle',
                true
            ],
            'assert property subTitle' => [
                'subTitle',
                'string',
                'getSubTitle',
                'setSubTitle',
                true
            ],
            'assert property description' => [
                'description',
                'string',
                'getDescription',
                'setDescription',
                true
            ],
            'assert property mainPicture' => [
                'mainPicture',
                'string',
                'getMainPicture',
                'setMainPicture',
                true
            ],
            'assert property pictureList' => [
                'pictureList',
                'string[]',
                'getPictureList',
                'setPictureList',
                true
            ],
            'assert property channelAttributeList' => [
                'channelAttributeList',
                '\JTL\SCX\Lib\Channel\Client\Model\ChannelAttribute[]',
                'getChannelAttributeList',
                'setChannelAttributeList',
                true
            ],
            'assert property variationList' => [
                'variationList',
                '\JTL\SCX\Lib\Channel\Client\Model\Variation[]',
                'getVariationList',
                'setVariationList',
                true
            ],
            'assert property sku' => [
                'sku',
                'string',
                'getSku',
                'setSku',
                false
            ],
            'assert property gtin' => [
                'gtin',
                'string',
                'getGtin',
                'setGtin',
                true
            ],
            'assert property mpn' => [
                'mpn',
                'string',
                'getMpn',
                'setMpn',
                true
            ],
            'assert property isbn' => [
                'isbn',
                'string',
                'getIsbn',
                'setIsbn',
                true
            ],
            'assert property brand' => [
                'brand',
                'string',
                'getBrand',
                'setBrand',
                true
            ],
            'assert property srp' => [
                'srp',
                '\JTL\SCX\Lib\Channel\Client\Model\Price',
                'getSrp',
                'setSrp',
                true
            ],
            'assert property productAttributeList' => [
                'productAttributeList',
                '\JTL\SCX\Lib\Channel\Client\Model\ProductAttribute[]',
                'getProductAttributeList',
                'setProductAttributeList',
                true
            ],
            'assert property channel' => [
                'channel',
                'string',
                'getChannel',
                'setChannel',
                false
            ],
            'assert property reportType' => [
                'reportType',
                '\JTL\SCX\Lib\Channel\Client\Model\ReportType',
                'getReportType',
                'setReportType',
                false
            ],
            'assert property options' => [
                'options',
                '\JTL\SCX\Lib\Channel\Client\Model\ReportRequestOptions',
                'getOptions',
                'setOptions',
                true
            ],
            'assert property startDate' => [
                'startDate',
                '\DateTime',
                'getStartDate',
                'setStartDate',
                true
            ],
            'assert property endDate' => [
                'endDate',
                '\DateTime',
                'getEndDate',
                'setEndDate',
                true
            ],
            'assert property reportId' => [
                'reportId',
                'string',
                'getReportId',
                'setReportId',
                false
            ],
            'assert property message' => [
                'message',
                'string',
                'getMessage',
                'setMessage',
                false
            ],
            'assert property severity' => [
                'severity',
                'string',
                'getSeverity',
                'setSeverity',
                false
            ],
            'assert property reason' => [
                'reason',
                '\JTL\SCX\Lib\Channel\Client\Model\CancelReason',
                'getReason',
                'setReason',
                false
            ],
            'assert property unlinkedAt' => [
                'unlinkedAt',
                '\DateTime',
                'getUnlinkedAt',
                'setUnlinkedAt',
                false
            ],
            'assert property permanentlyRemoved' => [
                'permanentlyRemoved',
                'bool',
                'getPermanentlyRemoved',
                'setPermanentlyRemoved',
                false
            ],
            'assert property orderCancellationRequestId' => [
                'orderCancellationRequestId',
                'string',
                'getOrderCancellationRequestId',
                'setOrderCancellationRequestId',
                false
            ],
            'assert property orderItem' => [
                'orderItem',
                '\JTL\SCX\Lib\Channel\Client\Model\RefundOrderItem[]',
                'getOrderItem',
                'setOrderItem',
                false
            ],
            'assert property cancelReason' => [
                'cancelReason',
                '\JTL\SCX\Lib\Channel\Client\Model\CancelReason',
                'getCancelReason',
                'setCancelReason',
                true
            ],
            'assert property orderAccepted' => [
                'orderAccepted',
                'bool',
                'getOrderAccepted',
                'setOrderAccepted',
                true
            ],
            'assert property type' => [
                'type',
                '\JTL\SCX\Lib\Channel\Client\Model\InvoiceDocumentType',
                'getType',
                'setType',
                false
            ],
            'assert property invoiceNumber' => [
                'invoiceNumber',
                'string',
                'getInvoiceNumber',
                'setInvoiceNumber',
                false
            ],
            'assert property documentId' => [
                'documentId',
                'string',
                'getDocumentId',
                'setDocumentId',
                false
            ],
            'assert property documentExpiresAt' => [
                'documentExpiresAt',
                '\DateTime',
                'getDocumentExpiresAt',
                'setDocumentExpiresAt',
                false
            ],
            'assert property sellerReturnId' => [
                'sellerReturnId',
                'string',
                'getSellerReturnId',
                'setSellerReturnId',
                false
            ],
            'assert property channelReturnId' => [
                'channelReturnId',
                'string',
                'getChannelReturnId',
                'setChannelReturnId',
                true
            ],
            'assert property refundId' => [
                'refundId',
                'string',
                'getRefundId',
                'setRefundId',
                false
            ],
            'assert property ticketId' => [
                'ticketId',
                'string',
                'getTicketId',
                'setTicketId',
                false
            ],
            'assert property replyRequested' => [
                'replyRequested',
                'bool',
                'getReplyRequested',
                'setReplyRequested',
                false
            ],
            'assert property createdAt' => [
                'createdAt',
                '\DateTime',
                'getCreatedAt',
                'setCreatedAt',
                false
            ],
            'assert property from' => [
                'from',
                '\JTL\SCX\Lib\Channel\Client\Model\TicketFrom',
                'getFrom',
                'setFrom',
                false
            ],
            'assert property attachment' => [
                'attachment',
                '\JTL\SCX\Lib\Channel\Client\Model\TicketAttachment[]',
                'getAttachment',
                'setAttachment',
                true
            ],
        ];
    }

    /**
     * @test
     * @dataProvider expectedInterface
     */
    public function it_has_expected_interface(string $property, string $type, string $expectedGetter, string $expectedSetter, bool $isNullable): void
    {
        $sample = $this->buildSampleForDataType($type);
        $sut = new SellerEventListEventListInnerEvent([$property => $sample]);

        $this->assertMethodExists($sut, $expectedGetter);
        $this->assertSame($sample, $sut->$expectedGetter());

        $this->assertArrayHasKey($property, $sut);
        $this->assertSame($sample, $sut[$property]);

        $newSample = $this->buildSampleForDataType($type);
        $this->assertMethodExists($sut, $expectedSetter);
        $sut->$expectedSetter($newSample);
        $this->assertSame($newSample, $sut[$property]);

        if ($isNullable) {
            $sut = new SellerEventListEventListInnerEvent([$property => null]);
            $this->assertNull($sut->$expectedGetter());

            $sut->$expectedSetter(null);
            $this->assertNull($sut->$expectedGetter());
        }
    }

}
