<?php
/**
 * ShippingAttributeLevelTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\AbstractApiModelTest;

/**
 * ShippingAttributeLevelTest Class Doc Comment
 *
 * @category    Class
 * @description Defines on which entity a shipping attribute is captured.  * Level **ORDER_ITEM** the attribute value is captured per order item (e.g. &#x60;IMEI&#x60;, &#x60;SERIAL_NUMBER&#x60;). * Level **SHIPMENT** the attribute value is captured per shipment (e.g. &#x60;DELIVERY_NOTE_NUMBER&#x60;).
 * @package     JTL\SCX\Lib\Channel\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Lib\Channel\Client\Model\ShippingAttributeLevel
 */
class ShippingAttributeLevelTest extends AbstractApiModelTest
{
    /**
     * Test Enum Value "ORDER_ITEM"
     * @test
     */
    public function is_a_const_ORDER_ITEM(): void
    {
        self::assertEquals('ORDER_ITEM', ShippingAttributeLevel::ORDER_ITEM);
        $sut = new ShippingAttributeLevel('ORDER_ITEM');
        self::assertEquals('ORDER_ITEM', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "ORDER_ITEM"
     * @test
     */
    public function it_can_be_constructed_forORDER_ITEM(): void
    {
        $sut = ShippingAttributeLevel::ORDER_ITEM();
        self::assertInstanceOf(ShippingAttributeLevel::class, $sut);
    }
    /**
     * Test Enum Value "SHIPMENT"
     * @test
     */
    public function is_a_const_SHIPMENT(): void
    {
        self::assertEquals('SHIPMENT', ShippingAttributeLevel::SHIPMENT);
        $sut = new ShippingAttributeLevel('SHIPMENT');
        self::assertEquals('SHIPMENT', $sut->getValue());
    }

    /**
     * Test Enum Value Named Constructor "SHIPMENT"
     * @test
     */
    public function it_can_be_constructed_forSHIPMENT(): void
    {
        $sut = ShippingAttributeLevel::SHIPMENT();
        self::assertInstanceOf(ShippingAttributeLevel::class, $sut);
    }

    /**
     * Test allowed values from Enum
     * @test
     */
    public function it_has_correct_set_of_allowed_values(): void
    {
        $allowed = [
            ShippingAttributeLevel::ORDER_ITEM,
            ShippingAttributeLevel::SHIPMENT,
        ];
        self::assertEquals($allowed, ShippingAttributeLevel::getAllowableEnumValues());
    }

}
