<?php
/**
 * StockListTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JTL-Channel API
 *
 * JTL-Channel API is a REST-based API that helps a Channel Integrator to connect Marketplace with the JTL-Wawi  ERP System.  # Key Features  With the JTL-Channel API, you can:    * Describe connected Marketplace Data Structure by providing Category and Attribute Data   * Manage Product and Offer Listings   * Manage Orders    * Handle the Post Order Process  # Development Guide  There is a detailed development guide available at [developer.jtl-software.com](https://developer.jtl-software.com/products/marketplaces/scx-channel-api/change_log).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use PHPUnit\Framework\TestCase;

/**
 * StockListTest Class Doc Comment
 *
 * @category    Class
 * @description Response containing a list of stock updates and the timestamp of the last update
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
/** @covers \JTL\SCX\Lib\Channel\Client\Model\StockList */
class StockListTest extends TestCase
{
    public function testStockList()
    {
        $dateTime = new \DateTime();
        $stock = new Stock([
            'sellerId' => 'sellerId',
            'offerId' => 'offerId',
            'channelOfferId' => 'channelOfferId',
            'quantity' => 1,
            'updatedAt' => $dateTime,
        ]);
        $data = [
            'stockUpdateList' => [
                $stock,
            ],
            'lastUpdatedAt' => $dateTime,
        ];
        $stockList = new StockList($data);

        self::assertNotNull($stockList);
        self::assertNotNull($stockList->getStockUpdateList());
        self::assertEquals($dateTime, $stockList->getLastUpdatedAt());
        self::assertCount(1, $stockList->getStockUpdateList());
        self::assertInstanceOf(Stock::class, $stockList->getStockUpdateList()[0]);
        self::assertEquals($stock, $stockList->getStockUpdateList()[0]);
        self::assertInstanceOf(\DateTime::class, $stockList->getLastUpdatedAt());
    }
}
