services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    JTL\SCX\Lib\Channel\Core\Command\AbstractCommand:
      tags: ['console.command']
    JTL\Nachricht\Contract\Listener\Listener:
      public: true

  JTL\SCX\Lib\Channel\:
    resource: '../src/*'
    exclude: '../src/{Core/AbstractApplicationContext.php}'

  # ###########################################################################
  # Logging Service
  # ###########################################################################
  Psr\Log\LoggerInterface: '@Monolog\Logger'

  JTL\SCX\Lib\Channel\Core\Log\MonologFactory: ~

  Psr\Container\ContainerInterface: '@service_container'

  Monolog\Logger:
    factory: ['@JTL\SCX\Lib\Channel\Core\Log\MonologFactory', 'create']
    arguments:
      $globalLogLevel: '%env(LOG_LEVEL)%'
      $logFile: '%env(LOG_FILE)%'
      $channel: '%env(LOG_CHANNEL)%'

  JTL\SCX\Lib\Channel\Contract\Core\Log\ScxLogger: '@JTL\SCX\Lib\Channel\Core\Log\ContextLogger'

  # ###########################################################################
  # SCX Channel-API service
  # ###########################################################################
  JTL\SCX\Client\:
    resource: './vendor/jtl-scx/api-base-client/src/*'

  JTL\SCX\Client\Api\Configuration:
    arguments:
      $host: '%env(SCX_CHANNEL_API_HOST)%'
      $refreshToken: '%env(SCX_CHANNEL_API_REFRESH_TOKEN)%'

  JTL\SCX\Lib\Channel\Contract\MetaData\MetaCategoryLoader:
    class: JTL\SCX\Lib\Channel\MetaData\DefaultMetaCategoryLoader

  JTL\SCX\Lib\Channel\Contract\MetaData\MetaDataAttributeLoader:
    class: JTL\SCX\Lib\Channel\MetaData\Attribute\DefaultMetaDataAttributeLoader

  JTL\SCX\Lib\Channel\Contract\Core\Lock\LockProvider:
    class: JTL\SCX\Lib\Channel\Core\Lock\DefaultLockProvider

  JTL\SCX\Lib\Channel\Core\Lock\LockCreator:
    shared: false

  Psr\Clock\ClockInterface: '@JTL\SCX\Lib\Channel\Helper\Clock'

  # ###########################################################################
  # Message Broker service
  # ###########################################################################
  JTL\Nachricht\:
    resource: './vendor/jtl/nachricht/src/*'

  JTL\Nachricht\Contract\Emitter\Emitter: '@JTL\Nachricht\Emitter\AmqpEmitter'

  JTL\Nachricht\Transport\Amqp\AmqpTransportFactory: ~

  JTL\Nachricht\Transport\Amqp\AmqpTransport:
    public: true
    factory: ['@JTL\Nachricht\Transport\Amqp\AmqpTransportFactory', 'createTransport']
    arguments:
      - host: '%env(RABBITMQ_HOST)%'
        port: '%env(RABBITMQ_PORT)%'
        httpPort: '%env(RABBITMQ_HTTP_PORT)%'
        user: '%env(RABBITMQ_USER)%'
        password: '%env(RABBITMQ_PASS)%'
        vhost: '%env(RABBITMQ_VHOST)%'
      - '@JTL\Nachricht\Contract\Serializer\MessageSerializer'

  JTL\Nachricht\Contract\Transport\Amqp\AmqpQueueLister:
    class: JTL\SCX\Lib\Channel\Core\RabbitMqManagementApi\RabbitMqQueueLister

  JTL\Nachricht\Contract\Message\MessageCounter:
    class: JTL\SCX\Lib\Channel\Core\Metrics\AmqpMessageCounter

  JTL\GoPrometrics\Client\GoPometricsConfigurator:
    class: JTL\SCX\Lib\Channel\Core\Metrics\AmqpMetricsConfigurator

  GuzzleHttp\Client:
    public: true

  # ###########################################################################
  # Template service
  # ###########################################################################
  JTL\SCX\Lib\Channel\Template\TwigTemplateRenderer:
    public: true

  # ###########################################################################
  # Translation Service
  # ###########################################################################
  JTL\SCX\Lib\Channel\Core\I18n\Translator:
    factory: [ '@JTL\SCX\Lib\Channel\Core\I18n\TranslatorFactory', 'createTranslator' ]
    arguments:
      - '%env(TRANSLATIONS_DIR)%'
      - '%env(DEFAULT_LOCALE)%'

  # ###########################################################################
  # Mongo Database Service
  # ###########################################################################
  JTL\SCX\Lib\Channel\Database\DatabaseConnectionCredentials:
    arguments: [ '%env(MONGODB_DSN)%', '%env(MONGODB_USERNAME)%', '%env(MONGODB_PASSWORD)%', '%env(MONGODB_DB)%' ]
