<?php
/**
 * ChannelNotificationReferenceType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\EnumInterface;

/**
 * ChannelNotificationReferenceType Class Doc Comment
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChannelNotificationReferenceType implements EnumInterface
{
    private $value;

    /**
     * Possible values of this enum
     */
    public const OFFER = 'OFFER';
    public const CHANNELOFFER = 'CHANNELOFFER';
    public const ORDERITEMID = 'ORDERITEMID';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OFFER,
            self::CHANNELOFFER,
            self::ORDERITEMID,
        ];
    }


    public static function OFFER(): ChannelNotificationReferenceType
    {
        return new self('OFFER');
    }

    public static function CHANNELOFFER(): ChannelNotificationReferenceType
    {
        return new self('CHANNELOFFER');
    }

    public static function ORDERITEMID(): ChannelNotificationReferenceType
    {
        return new self('ORDERITEMID');
    }


    public function __construct($value)
    {
        $this->value = $value;
    }

    public function getValue()
    {
        return $this->value;
    }
}
