<?php
/**
 * ChannelSeller
 *
 * PHP version 8.4
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use ArrayAccess;
use JTL\SCX\Lib\Channel\Client\ObjectSerializer;

/**
 * ChannelSeller Class Doc Comment
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ChannelSeller implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      */
    protected static string $openAPIModelName = 'ChannelSeller';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      *
      */
    protected static array $openAPITypes = [
        'sellerId' => 'string',
        'jtlAccountId' => 'int',
        'companyName' => 'string',
        'isActiveByJTL' => 'bool',
        'isActiveByChannel' => 'bool',
        'createdAt' => '\DateTime',
        'updatedAt' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'sellerId' => null,
        'jtlAccountId' => null,
        'companyName' => null,
        'isActiveByJTL' => null,
        'isActiveByChannel' => null,
        'createdAt' => 'date-time',
        'updatedAt' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    protected static array $attributeMap = [
        'sellerId' => 'sellerId',
        'jtlAccountId' => 'jtlAccountId',
        'companyName' => 'companyName',
        'isActiveByJTL' => 'isActiveByJTL',
        'isActiveByChannel' => 'isActiveByChannel',
        'createdAt' => 'createdAt',
        'updatedAt' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    protected static array $setters = [
        'sellerId' => 'setSellerId',
        'jtlAccountId' => 'setJtlAccountId',
        'companyName' => 'setCompanyName',
        'isActiveByJTL' => 'setIsActiveByJTL',
        'isActiveByChannel' => 'setIsActiveByChannel',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    protected static array $getters = [
        'sellerId' => 'getSellerId',
        'jtlAccountId' => 'getJtlAccountId',
        'companyName' => 'getCompanyName',
        'isActiveByJTL' => 'getIsActiveByJTL',
        'isActiveByChannel' => 'getIsActiveByChannel',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     * @codeCoverageIgnore
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @codeCoverageIgnore
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @codeCoverageIgnore
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     * @codeCoverageIgnore
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }





    /**
     * Associative array for storing property values
     */
    protected array $container = [];

    public function __construct(array|null $data = null)
    {
        $this->container['sellerId'] = $data['sellerId'] ?? null;
        $this->container['jtlAccountId'] = $data['jtlAccountId'] ?? null;
        $this->container['companyName'] = $data['companyName'] ?? null;
        $this->container['isActiveByJTL'] = $data['isActiveByJTL'] ?? true;
        $this->container['isActiveByChannel'] = $data['isActiveByChannel'] ?? true;
        $this->container['createdAt'] = $data['createdAt'] ?? null;
        $this->container['updatedAt'] = $data['updatedAt'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     * @codeCoverageIgnore
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['sellerId']) && !preg_match("/^\\w{1,50}$/", $this->container['sellerId'])) {
            $invalidProperties[] = "invalid value for 'sellerId', must be conform to the pattern /^\\w{1,50}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     * @codeCoverageIgnore
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    public function getSellerId(): ?string
    {
        return $this->container['sellerId'];
    }

    public function setSellerId(?string $sellerId): ChannelSeller
    {
        $this->container['sellerId'] = $sellerId;
        return $this;
    }


    public function getJtlAccountId(): ?int
    {
        return $this->container['jtlAccountId'];
    }

    public function setJtlAccountId(?int $jtlAccountId): ChannelSeller
    {
        $this->container['jtlAccountId'] = $jtlAccountId;
        return $this;
    }


    public function getCompanyName(): ?string
    {
        return $this->container['companyName'];
    }

    public function setCompanyName(?string $companyName): ChannelSeller
    {
        $this->container['companyName'] = $companyName;
        return $this;
    }


    public function getIsActiveByJTL(): ?bool
    {
        return $this->container['isActiveByJTL'];
    }

    public function setIsActiveByJTL(?bool $isActiveByJTL): ChannelSeller
    {
        $this->container['isActiveByJTL'] = $isActiveByJTL;
        return $this;
    }


    public function getIsActiveByChannel(): ?bool
    {
        return $this->container['isActiveByChannel'];
    }

    public function setIsActiveByChannel(?bool $isActiveByChannel): ChannelSeller
    {
        $this->container['isActiveByChannel'] = $isActiveByChannel;
        return $this;
    }


    public function getCreatedAt(): ?\DateTime
    {
        return $this->container['createdAt'];
    }

    public function setCreatedAt(?\DateTime $createdAt): ChannelSeller
    {
        $this->container['createdAt'] = $createdAt;
        return $this;
    }


    public function getUpdatedAt(): ?\DateTime
    {
        return $this->container['updatedAt'];
    }

    public function setUpdatedAt(?\DateTime $updatedAt): ChannelSeller
    {
        $this->container['updatedAt'] = $updatedAt;
        return $this;
    }

    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     */
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     * @codeCoverageIgnore
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     * @codeCoverageIgnore
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     * @codeCoverageIgnore
     */
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     * @codeCoverageIgnore
     */
    public function __toString(): string
    {
        return json_encode(
            $this->jsonSerialize(),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     * @codeCoverageIgnore
     */
    public function toHeaderValue(): string
    {
        return json_encode($this->jsonSerialize());
    }
}
