<?php
/**
 * ChannelSelfUpdate
 *
 * PHP version 8.4
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use ArrayAccess;
use JTL\SCX\Lib\Channel\Client\ObjectSerializer;

/**
 * ChannelSelfUpdate Class Doc Comment
 *
 * @category Class
 * @description Channel master-data update payload — display name, currency, supported marketplaces, contact data and feature flags. Requires an MFA PIN.
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ChannelSelfUpdate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      */
    protected static string $openAPIModelName = 'ChannelSelfUpdate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @param ChannelFeatureList
      * @param MinimumClientsVersionRequired
      *
      */
    protected static array $openAPITypes = [
        'mfaPin' => 'string',
        'displayName' => 'string',
        'currency' => 'string',
        'marketplaceList' => 'string[]',
        'website' => 'string',
        'mfaContact' => 'string',
        'vendor' => 'string',
        'signUpUrl' => 'string',
        'updateUrl' => 'string',
        'featureList' => '\JTL\SCX\Lib\Channel\Client\Model\ChannelFeatureList',
        'minimumClientsVersionRequired' => '\JTL\SCX\Lib\Channel\Client\Model\MinimumClientsVersionRequired[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'mfaPin' => null,
        'displayName' => null,
        'currency' => null,
        'marketplaceList' => null,
        'website' => 'uri',
        'mfaContact' => 'email',
        'vendor' => null,
        'signUpUrl' => null,
        'updateUrl' => null,
        'featureList' => null,
        'minimumClientsVersionRequired' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    protected static array $attributeMap = [
        'mfaPin' => 'mfaPin',
        'displayName' => 'displayName',
        'currency' => 'currency',
        'marketplaceList' => 'marketplaceList',
        'website' => 'website',
        'mfaContact' => 'mfaContact',
        'vendor' => 'vendor',
        'signUpUrl' => 'signUpUrl',
        'updateUrl' => 'updateUrl',
        'featureList' => 'featureList',
        'minimumClientsVersionRequired' => 'minimumClientsVersionRequired'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    protected static array $setters = [
        'mfaPin' => 'setMfaPin',
        'displayName' => 'setDisplayName',
        'currency' => 'setCurrency',
        'marketplaceList' => 'setMarketplaceList',
        'website' => 'setWebsite',
        'mfaContact' => 'setMfaContact',
        'vendor' => 'setVendor',
        'signUpUrl' => 'setSignUpUrl',
        'updateUrl' => 'setUpdateUrl',
        'featureList' => 'setFeatureList',
        'minimumClientsVersionRequired' => 'setMinimumClientsVersionRequired'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    protected static array $getters = [
        'mfaPin' => 'getMfaPin',
        'displayName' => 'getDisplayName',
        'currency' => 'getCurrency',
        'marketplaceList' => 'getMarketplaceList',
        'website' => 'getWebsite',
        'mfaContact' => 'getMfaContact',
        'vendor' => 'getVendor',
        'signUpUrl' => 'getSignUpUrl',
        'updateUrl' => 'getUpdateUrl',
        'featureList' => 'getFeatureList',
        'minimumClientsVersionRequired' => 'getMinimumClientsVersionRequired'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     * @codeCoverageIgnore
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @codeCoverageIgnore
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @codeCoverageIgnore
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     * @codeCoverageIgnore
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }





    /**
     * Associative array for storing property values
     */
    protected array $container = [];

    public function __construct(array|null $data = null)
    {
        $this->container['mfaPin'] = $data['mfaPin'] ?? null;
        $this->container['displayName'] = $data['displayName'] ?? null;
        $this->container['currency'] = $data['currency'] ?? null;
        $this->container['marketplaceList'] = $data['marketplaceList'] ?? null;
        $this->container['website'] = $data['website'] ?? null;
        $this->container['mfaContact'] = $data['mfaContact'] ?? null;
        $this->container['vendor'] = $data['vendor'] ?? null;
        $this->container['signUpUrl'] = $data['signUpUrl'] ?? null;
        $this->container['updateUrl'] = $data['updateUrl'] ?? null;
        $this->container['featureList'] = $data['featureList'] ?? null;
        $this->container['minimumClientsVersionRequired'] = $data['minimumClientsVersionRequired'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     * @codeCoverageIgnore
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['mfaPin'] === null) {
            $invalidProperties[] = "'mfaPin' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     * @codeCoverageIgnore
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    public function getMfaPin(): string
    {
        return $this->container['mfaPin'];
    }

    public function setMfaPin(string $mfaPin): ChannelSelfUpdate
    {
        $this->container['mfaPin'] = $mfaPin;
        return $this;
    }


    public function getDisplayName(): ?string
    {
        return $this->container['displayName'];
    }

    public function setDisplayName(?string $displayName): ChannelSelfUpdate
    {
        $this->container['displayName'] = $displayName;
        return $this;
    }


    public function getCurrency(): ?string
    {
        return $this->container['currency'];
    }

    public function setCurrency(?string $currency): ChannelSelfUpdate
    {
        $this->container['currency'] = $currency;
        return $this;
    }


    public function getMarketplaceList(): ?array
    {
        return $this->container['marketplaceList'];
    }

    public function setMarketplaceList(?array $marketplaceList): ChannelSelfUpdate
    {
        $this->container['marketplaceList'] = $marketplaceList;
        return $this;
    }


    public function getWebsite(): ?string
    {
        return $this->container['website'];
    }

    public function setWebsite(?string $website): ChannelSelfUpdate
    {
        $this->container['website'] = $website;
        return $this;
    }


    public function getMfaContact(): ?string
    {
        return $this->container['mfaContact'];
    }

    public function setMfaContact(?string $mfaContact): ChannelSelfUpdate
    {
        $this->container['mfaContact'] = $mfaContact;
        return $this;
    }


    public function getVendor(): ?string
    {
        return $this->container['vendor'];
    }

    public function setVendor(?string $vendor): ChannelSelfUpdate
    {
        $this->container['vendor'] = $vendor;
        return $this;
    }


    public function getSignUpUrl(): ?string
    {
        return $this->container['signUpUrl'];
    }

    public function setSignUpUrl(?string $signUpUrl): ChannelSelfUpdate
    {
        $this->container['signUpUrl'] = $signUpUrl;
        return $this;
    }


    public function getUpdateUrl(): ?string
    {
        return $this->container['updateUrl'];
    }

    public function setUpdateUrl(?string $updateUrl): ChannelSelfUpdate
    {
        $this->container['updateUrl'] = $updateUrl;
        return $this;
    }


    public function getFeatureList(): ?ChannelFeatureList
    {
        return $this->container['featureList'];
    }

    public function setFeatureList(?ChannelFeatureList $featureList): ChannelSelfUpdate
    {
        $this->container['featureList'] = $featureList;
        return $this;
    }


    public function getMinimumClientsVersionRequired(): ?array
    {
        return $this->container['minimumClientsVersionRequired'];
    }

    public function setMinimumClientsVersionRequired(?array $minimumClientsVersionRequired): ChannelSelfUpdate
    {
        $this->container['minimumClientsVersionRequired'] = $minimumClientsVersionRequired;
        return $this;
    }

    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     */
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     * @codeCoverageIgnore
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     * @codeCoverageIgnore
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     * @codeCoverageIgnore
     */
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     * @codeCoverageIgnore
     */
    public function __toString(): string
    {
        return json_encode(
            $this->jsonSerialize(),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     * @codeCoverageIgnore
     */
    public function toHeaderValue(): string
    {
        return json_encode($this->jsonSerialize());
    }
}
