<?php
/**
 * SalesChannel
 *
 * PHP version 8.4
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use ArrayAccess;
use JTL\SCX\Lib\Channel\Client\ObjectSerializer;

/**
 * SalesChannel Class Doc Comment
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SalesChannel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      */
    protected static string $openAPIModelName = 'SalesChannel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @param ChannelFeatureList
      * @param MinimumClientsVersionRequired
      * @param MarketplaceChannelList
      * @param MarketplaceChannels
      *
      */
    protected static array $openAPITypes = [
        'group' => 'string',
        'currency' => 'string',
        'marketplaceList' => 'string[]',
        'supportedLanguages' => 'string[]',
        'displayName' => 'string',
        'website' => 'string',
        'pricing' => 'string',
        'channelType' => 'string',
        'supportContact' => 'string',
        'vendor' => 'string',
        'signUpUrl' => 'string',
        'updateUrl' => 'string',
        'logo' => 'string',
        'description' => 'string',
        'appId' => 'string',
        'featureList' => '\JTL\SCX\Lib\Channel\Client\Model\ChannelFeatureList',
        'minimumClientsVersionRequired' => '\JTL\SCX\Lib\Channel\Client\Model\MinimumClientsVersionRequired[]',
        'isPlatform' => 'bool',
        'platform' => 'string',
        'marketplaceChannelList' => '\JTL\SCX\Lib\Channel\Client\Model\MarketplaceChannelList',
        'stockSyncGroup' => 'string',
        'visibility' => 'string',
        'channel' => 'string',
        'marketplaceChannels' => '\JTL\SCX\Lib\Channel\Client\Model\MarketplaceChannels'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'group' => null,
        'currency' => null,
        'marketplaceList' => null,
        'supportedLanguages' => null,
        'displayName' => null,
        'website' => 'uri',
        'pricing' => 'uri',
        'channelType' => null,
        'supportContact' => 'email',
        'vendor' => null,
        'signUpUrl' => null,
        'updateUrl' => null,
        'logo' => null,
        'description' => null,
        'appId' => null,
        'featureList' => null,
        'minimumClientsVersionRequired' => null,
        'isPlatform' => null,
        'platform' => null,
        'marketplaceChannelList' => null,
        'stockSyncGroup' => null,
        'visibility' => null,
        'channel' => null,
        'marketplaceChannels' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    protected static array $attributeMap = [
        'group' => 'group',
        'currency' => 'currency',
        'marketplaceList' => 'marketplaceList',
        'supportedLanguages' => 'supportedLanguages',
        'displayName' => 'displayName',
        'website' => 'website',
        'pricing' => 'pricing',
        'channelType' => 'channelType',
        'supportContact' => 'supportContact',
        'vendor' => 'vendor',
        'signUpUrl' => 'signUpUrl',
        'updateUrl' => 'updateUrl',
        'logo' => 'logo',
        'description' => 'description',
        'appId' => 'appId',
        'featureList' => 'featureList',
        'minimumClientsVersionRequired' => 'minimumClientsVersionRequired',
        'isPlatform' => 'isPlatform',
        'platform' => 'platform',
        'marketplaceChannelList' => 'marketplaceChannelList',
        'stockSyncGroup' => 'stockSyncGroup',
        'visibility' => 'visibility',
        'channel' => 'channel',
        'marketplaceChannels' => 'marketplaceChannels'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    protected static array $setters = [
        'group' => 'setGroup',
        'currency' => 'setCurrency',
        'marketplaceList' => 'setMarketplaceList',
        'supportedLanguages' => 'setSupportedLanguages',
        'displayName' => 'setDisplayName',
        'website' => 'setWebsite',
        'pricing' => 'setPricing',
        'channelType' => 'setChannelType',
        'supportContact' => 'setSupportContact',
        'vendor' => 'setVendor',
        'signUpUrl' => 'setSignUpUrl',
        'updateUrl' => 'setUpdateUrl',
        'logo' => 'setLogo',
        'description' => 'setDescription',
        'appId' => 'setAppId',
        'featureList' => 'setFeatureList',
        'minimumClientsVersionRequired' => 'setMinimumClientsVersionRequired',
        'isPlatform' => 'setIsPlatform',
        'platform' => 'setPlatform',
        'marketplaceChannelList' => 'setMarketplaceChannelList',
        'stockSyncGroup' => 'setStockSyncGroup',
        'visibility' => 'setVisibility',
        'channel' => 'setChannel',
        'marketplaceChannels' => 'setMarketplaceChannels'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    protected static array $getters = [
        'group' => 'getGroup',
        'currency' => 'getCurrency',
        'marketplaceList' => 'getMarketplaceList',
        'supportedLanguages' => 'getSupportedLanguages',
        'displayName' => 'getDisplayName',
        'website' => 'getWebsite',
        'pricing' => 'getPricing',
        'channelType' => 'getChannelType',
        'supportContact' => 'getSupportContact',
        'vendor' => 'getVendor',
        'signUpUrl' => 'getSignUpUrl',
        'updateUrl' => 'getUpdateUrl',
        'logo' => 'getLogo',
        'description' => 'getDescription',
        'appId' => 'getAppId',
        'featureList' => 'getFeatureList',
        'minimumClientsVersionRequired' => 'getMinimumClientsVersionRequired',
        'isPlatform' => 'getIsPlatform',
        'platform' => 'getPlatform',
        'marketplaceChannelList' => 'getMarketplaceChannelList',
        'stockSyncGroup' => 'getStockSyncGroup',
        'visibility' => 'getVisibility',
        'channel' => 'getChannel',
        'marketplaceChannels' => 'getMarketplaceChannels'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     * @codeCoverageIgnore
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @codeCoverageIgnore
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @codeCoverageIgnore
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     * @codeCoverageIgnore
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const CHANNEL_TYPE_MARKETPLACE = 'MARKETPLACE';
    public const CHANNEL_TYPE_OTHER = 'OTHER';
    public const VISIBILITY_JTL = 'JTL';
    public const VISIBILITY_THIRDPARTY = 'THIRDPARTY';
    public const VISIBILITY_ONBOARDING = 'ONBOARDING';
    public const VISIBILITY_RESTRICTED = 'RESTRICTED';



    /**
     * Gets allowable values of the enum
     */
    public function getChannelTypeAllowableValues(): array
    {
        return [
            self::CHANNEL_TYPE_MARKETPLACE,
            self::CHANNEL_TYPE_OTHER,
        ];
    }

    /**
     * Gets allowable values of the enum
     */
    public function getVisibilityAllowableValues(): array
    {
        return [
            self::VISIBILITY_JTL,
            self::VISIBILITY_THIRDPARTY,
            self::VISIBILITY_ONBOARDING,
            self::VISIBILITY_RESTRICTED,
        ];
    }


    /**
     * Associative array for storing property values
     */
    protected array $container = [];

    public function __construct(array|null $data = null)
    {
        $this->container['group'] = $data['group'] ?? null;
        $this->container['currency'] = $data['currency'] ?? null;
        $this->container['marketplaceList'] = $data['marketplaceList'] ?? null;
        $this->container['supportedLanguages'] = $data['supportedLanguages'] ?? null;
        $this->container['displayName'] = $data['displayName'] ?? null;
        $this->container['website'] = $data['website'] ?? null;
        $this->container['pricing'] = $data['pricing'] ?? null;
        $this->container['channelType'] = $data['channelType'] ?? 'MARKETPLACE';
        $this->container['supportContact'] = $data['supportContact'] ?? null;
        $this->container['vendor'] = $data['vendor'] ?? null;
        $this->container['signUpUrl'] = $data['signUpUrl'] ?? null;
        $this->container['updateUrl'] = $data['updateUrl'] ?? null;
        $this->container['logo'] = $data['logo'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['appId'] = $data['appId'] ?? null;
        $this->container['featureList'] = $data['featureList'] ?? null;
        $this->container['minimumClientsVersionRequired'] = $data['minimumClientsVersionRequired'] ?? null;
        $this->container['isPlatform'] = $data['isPlatform'] ?? false;
        $this->container['platform'] = $data['platform'] ?? null;
        $this->container['marketplaceChannelList'] = $data['marketplaceChannelList'] ?? null;
        $this->container['stockSyncGroup'] = $data['stockSyncGroup'] ?? null;
        $this->container['visibility'] = $data['visibility'] ?? null;
        $this->container['channel'] = $data['channel'] ?? null;
        $this->container['marketplaceChannels'] = $data['marketplaceChannels'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     * @codeCoverageIgnore
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['marketplaceList'] === null) {
            $invalidProperties[] = "'marketplaceList' can't be null";
        }
        if ($this->container['displayName'] === null) {
            $invalidProperties[] = "'displayName' can't be null";
        }
        if ($this->container['website'] === null) {
            $invalidProperties[] = "'website' can't be null";
        }
        $allowedValues = $this->getChannelTypeAllowableValues();
        if (!is_null($this->container['channelType']) && !in_array($this->container['channelType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'channelType', must be one of '%s'",
                $this->container['channelType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['supportContact'] === null) {
            $invalidProperties[] = "'supportContact' can't be null";
        }
        if ($this->container['vendor'] === null) {
            $invalidProperties[] = "'vendor' can't be null";
        }
        if ($this->container['signUpUrl'] === null) {
            $invalidProperties[] = "'signUpUrl' can't be null";
        }
        if ($this->container['featureList'] === null) {
            $invalidProperties[] = "'featureList' can't be null";
        }
        $allowedValues = $this->getVisibilityAllowableValues();
        if (!is_null($this->container['visibility']) && !in_array($this->container['visibility'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'visibility', must be one of '%s'",
                $this->container['visibility'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['channel'] === null) {
            $invalidProperties[] = "'channel' can't be null";
        }
        if (!preg_match("/^\\w{5,15}$/", $this->container['channel'])) {
            $invalidProperties[] = "invalid value for 'channel', must be conform to the pattern /^\\w{5,15}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     * @codeCoverageIgnore
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    public function getGroup(): ?string
    {
        return $this->container['group'];
    }

    public function setGroup(?string $group): SalesChannel
    {
        $this->container['group'] = $group;
        return $this;
    }


    public function getCurrency(): ?string
    {
        return $this->container['currency'];
    }

    public function setCurrency(?string $currency): SalesChannel
    {
        $this->container['currency'] = $currency;
        return $this;
    }


    public function getMarketplaceList(): array
    {
        return $this->container['marketplaceList'];
    }

    public function setMarketplaceList(array $marketplaceList): SalesChannel
    {
        $this->container['marketplaceList'] = $marketplaceList;
        return $this;
    }


    public function getSupportedLanguages(): ?array
    {
        return $this->container['supportedLanguages'];
    }

    public function setSupportedLanguages(?array $supportedLanguages): SalesChannel
    {
        $this->container['supportedLanguages'] = $supportedLanguages;
        return $this;
    }


    public function getDisplayName(): string
    {
        return $this->container['displayName'];
    }

    public function setDisplayName(string $displayName): SalesChannel
    {
        $this->container['displayName'] = $displayName;
        return $this;
    }


    public function getWebsite(): string
    {
        return $this->container['website'];
    }

    public function setWebsite(string $website): SalesChannel
    {
        $this->container['website'] = $website;
        return $this;
    }


    public function getPricing(): ?string
    {
        return $this->container['pricing'];
    }

    public function setPricing(?string $pricing): SalesChannel
    {
        $this->container['pricing'] = $pricing;
        return $this;
    }


    public function getChannelType(): ?string
    {
        return $this->container['channelType'];
    }

    public function setChannelType(?string $channelType): SalesChannel
    {
        $this->container['channelType'] = $channelType;
        return $this;
    }


    public function getSupportContact(): string
    {
        return $this->container['supportContact'];
    }

    public function setSupportContact(string $supportContact): SalesChannel
    {
        $this->container['supportContact'] = $supportContact;
        return $this;
    }


    public function getVendor(): string
    {
        return $this->container['vendor'];
    }

    public function setVendor(string $vendor): SalesChannel
    {
        $this->container['vendor'] = $vendor;
        return $this;
    }


    public function getSignUpUrl(): string
    {
        return $this->container['signUpUrl'];
    }

    public function setSignUpUrl(string $signUpUrl): SalesChannel
    {
        $this->container['signUpUrl'] = $signUpUrl;
        return $this;
    }


    public function getUpdateUrl(): ?string
    {
        return $this->container['updateUrl'];
    }

    public function setUpdateUrl(?string $updateUrl): SalesChannel
    {
        $this->container['updateUrl'] = $updateUrl;
        return $this;
    }


    public function getLogo(): ?string
    {
        return $this->container['logo'];
    }

    public function setLogo(?string $logo): SalesChannel
    {
        $this->container['logo'] = $logo;
        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    public function setDescription(?string $description): SalesChannel
    {
        $this->container['description'] = $description;
        return $this;
    }


    public function getAppId(): ?string
    {
        return $this->container['appId'];
    }

    public function setAppId(?string $appId): SalesChannel
    {
        $this->container['appId'] = $appId;
        return $this;
    }


    public function getFeatureList(): ChannelFeatureList
    {
        return $this->container['featureList'];
    }

    public function setFeatureList(ChannelFeatureList $featureList): SalesChannel
    {
        $this->container['featureList'] = $featureList;
        return $this;
    }


    public function getMinimumClientsVersionRequired(): ?array
    {
        return $this->container['minimumClientsVersionRequired'];
    }

    public function setMinimumClientsVersionRequired(?array $minimumClientsVersionRequired): SalesChannel
    {
        $this->container['minimumClientsVersionRequired'] = $minimumClientsVersionRequired;
        return $this;
    }


    public function getIsPlatform(): ?bool
    {
        return $this->container['isPlatform'];
    }

    public function setIsPlatform(?bool $isPlatform): SalesChannel
    {
        $this->container['isPlatform'] = $isPlatform;
        return $this;
    }


    public function getPlatform(): ?string
    {
        return $this->container['platform'];
    }

    public function setPlatform(?string $platform): SalesChannel
    {
        $this->container['platform'] = $platform;
        return $this;
    }


    public function getMarketplaceChannelList(): ?MarketplaceChannelList
    {
        return $this->container['marketplaceChannelList'];
    }

    public function setMarketplaceChannelList(?MarketplaceChannelList $marketplaceChannelList): SalesChannel
    {
        $this->container['marketplaceChannelList'] = $marketplaceChannelList;
        return $this;
    }


    public function getStockSyncGroup(): ?string
    {
        return $this->container['stockSyncGroup'];
    }

    public function setStockSyncGroup(?string $stockSyncGroup): SalesChannel
    {
        $this->container['stockSyncGroup'] = $stockSyncGroup;
        return $this;
    }


    public function getVisibility(): ?string
    {
        return $this->container['visibility'];
    }

    public function setVisibility(?string $visibility): SalesChannel
    {
        $this->container['visibility'] = $visibility;
        return $this;
    }


    public function getChannel(): string
    {
        return $this->container['channel'];
    }

    public function setChannel(string $channel): SalesChannel
    {
        $this->container['channel'] = $channel;
        return $this;
    }


    public function getMarketplaceChannels(): ?MarketplaceChannels
    {
        return $this->container['marketplaceChannels'];
    }

    public function setMarketplaceChannels(?MarketplaceChannels $marketplaceChannels): SalesChannel
    {
        $this->container['marketplaceChannels'] = $marketplaceChannels;
        return $this;
    }

    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     */
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     * @codeCoverageIgnore
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     * @codeCoverageIgnore
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     * @codeCoverageIgnore
     */
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     * @codeCoverageIgnore
     */
    public function __toString(): string
    {
        return json_encode(
            $this->jsonSerialize(),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     * @codeCoverageIgnore
     */
    public function toHeaderValue(): string
    {
        return json_encode($this->jsonSerialize());
    }
}
