<?php
/**
 * SellerEventListEventList
 *
 * PHP version 8.4
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use ArrayAccess;
use JTL\SCX\Lib\Channel\Client\ObjectSerializer;

/**
 * SellerEventListEventList Class Doc Comment
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SellerEventListEventList implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    protected static string $openAPIModelName = 'SellerEventList_eventList';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @param SellerEventTypeList
     * @param object
     *
     */
    protected static array $openAPITypes = [
        'id' => 'string',
        'createdAt' => '\DateTime',
        'clientVersion' => 'string',
        'type' => '\JTL\SCX\Lib\Channel\Client\Model\SellerEventTypeList',
        'event' => 'OneOfSellerEventOrderShippingSellerEventOrderPaymentSellerEventOfferEndSellerEventOfferNewSellerEventOfferUpdateSellerEventOfferStockUpdateSellerEventOfferPriceUpdateSellerEventTestSellerEventReportRequestSystemEventNotificationSellerEventChannelUnlinkedSellerEventSellerAttributesUpdateRequestSellerEventOrderCancellationRequestSellerEventOrderCancellationAcceptedSellerEventOrderCancellationDeniedSellerEventOrderAcceptSellerEventOrderInvoiceSellerEventOrderReturnReceivedSellerEventOrderRefundSellerEventTicketReply'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'id' => null,
        'createdAt' => 'date-time',
        'clientVersion' => null,
        'type' => null,
        'event' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'createdAt' => 'createdAt',
        'clientVersion' => 'clientVersion',
        'type' => 'type',
        'event' => 'event'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    protected static array $setters = [
        'id' => 'setId',
        'createdAt' => 'setCreatedAt',
        'clientVersion' => 'setClientVersion',
        'type' => 'setType',
        'event' => 'setEvent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    protected static array $getters = [
        'id' => 'getId',
        'createdAt' => 'getCreatedAt',
        'clientVersion' => 'getClientVersion',
        'type' => 'getType',
        'event' => 'getEvent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     * @codeCoverageIgnore
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @codeCoverageIgnore
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @codeCoverageIgnore
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     * @codeCoverageIgnore
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }





    /**
     * Associative array for storing property values
     */
    protected array $container = [];

    public function __construct(array|null $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['createdAt'] = $data['createdAt'] ?? null;
        $this->container['clientVersion'] = $data['clientVersion'] ?? null;
        $this->container['type'] = $data['type'] ?? null;
        $this->container['event'] = $data['event'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     * @codeCoverageIgnore
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if (!is_null($this->container['clientVersion']) && !preg_match("/^\\w{1,25}$/", $this->container['clientVersion'])) {
            $invalidProperties[] = "invalid value for 'clientVersion', must be conform to the pattern /^\\w{1,25}$/.";
        }

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['event'] === null) {
            $invalidProperties[] = "'event' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     * @codeCoverageIgnore
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    public function getId(): string
    {
        return $this->container['id'];
    }

    public function setId(string $id): SellerEventListEventList
    {
        $this->container['id'] = $id;
        return $this;
    }


    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    public function setCreatedAt(\DateTime $createdAt): SellerEventListEventList
    {
        $this->container['createdAt'] = $createdAt;
        return $this;
    }


    public function getClientVersion(): ?string
    {
        return $this->container['clientVersion'];
    }

    public function setClientVersion(?string $clientVersion): SellerEventListEventList
    {
        $this->container['clientVersion'] = $clientVersion;
        return $this;
    }


    public function getType(): SellerEventTypeList
    {
        return $this->container['type'];
    }

    public function setType(SellerEventTypeList $type): SellerEventListEventList
    {
        $this->container['type'] = $type;
        return $this;
    }


    public function getEvent(): object
    {
        return $this->container['event'];
    }

    public function setEvent(object $event): SellerEventListEventList
    {
        $this->container['event'] = $event;
        return $this;
    }

    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     */
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     * @codeCoverageIgnore
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     * @codeCoverageIgnore
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     * @codeCoverageIgnore
     */
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     * @codeCoverageIgnore
     */
    public function __toString(): string
    {
        return json_encode(
            $this->jsonSerialize(),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     * @codeCoverageIgnore
     */
    public function toHeaderValue(): string
    {
        return json_encode($this->jsonSerialize());
    }
}
