<?php
/**
 * SellerEventListEventListInnerEvent
 *
 * PHP version 8.4
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use ArrayAccess;
use JTL\SCX\Lib\Channel\Client\ObjectSerializer;

/**
 * SellerEventListEventListInnerEvent Class Doc Comment
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SellerEventListEventListInnerEvent implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      */
    protected static string $openAPIModelName = 'SellerEventList_eventList_inner_event';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @param OrderShippingPosition
      * @param PriceContainer
      * @param ChannelAttribute
      * @param Variation
      * @param Price
      * @param ProductAttribute
      * @param ReportType
      * @param ReportRequestOptions
      * @param CancelReason
      * @param RefundOrderItem
      * @param CancelReason
      * @param InvoiceDocumentType
      * @param TicketFrom
      * @param TicketAttachment
      *
      */
    protected static array $openAPITypes = [
        'sellerId' => 'string',
        'orderId' => 'string',
        'shippingComplete' => 'bool',
        'shippingItems' => '\JTL\SCX\Lib\Channel\Client\Model\OrderShippingPosition[]',
        'paymentComplete' => 'bool',
        'paidAt' => '\DateTime',
        'offerId' => 'int',
        'channelOfferId' => 'string',
        'parentOfferId' => 'int',
        'channelCategoryId' => 'string',
        'quantity' => 'string',
        'taxPercent' => 'string',
        'priceList' => '\JTL\SCX\Lib\Channel\Client\Model\PriceContainer[]',
        'title' => 'string',
        'subTitle' => 'string',
        'description' => 'string',
        'mainPicture' => 'string',
        'pictureList' => 'string[]',
        'channelAttributeList' => '\JTL\SCX\Lib\Channel\Client\Model\ChannelAttribute[]',
        'variationList' => '\JTL\SCX\Lib\Channel\Client\Model\Variation[]',
        'sku' => 'string',
        'gtin' => 'string',
        'mpn' => 'string',
        'isbn' => 'string',
        'brand' => 'string',
        'srp' => '\JTL\SCX\Lib\Channel\Client\Model\Price',
        'productAttributeList' => '\JTL\SCX\Lib\Channel\Client\Model\ProductAttribute[]',
        'channel' => 'string',
        'reportType' => '\JTL\SCX\Lib\Channel\Client\Model\ReportType',
        'options' => '\JTL\SCX\Lib\Channel\Client\Model\ReportRequestOptions',
        'startDate' => '\DateTime',
        'endDate' => '\DateTime',
        'reportId' => 'string',
        'message' => 'string',
        'severity' => 'string',
        'reason' => '\JTL\SCX\Lib\Channel\Client\Model\CancelReason',
        'unlinkedAt' => '\DateTime',
        'permanentlyRemoved' => 'bool',
        'orderCancellationRequestId' => 'string',
        'orderItem' => '\JTL\SCX\Lib\Channel\Client\Model\RefundOrderItem[]',
        'cancelReason' => '\JTL\SCX\Lib\Channel\Client\Model\CancelReason',
        'orderAccepted' => 'bool',
        'type' => '\JTL\SCX\Lib\Channel\Client\Model\InvoiceDocumentType',
        'invoiceNumber' => 'string',
        'documentId' => 'string',
        'documentExpiresAt' => '\DateTime',
        'sellerReturnId' => 'string',
        'channelReturnId' => 'string',
        'refundId' => 'string',
        'ticketId' => 'string',
        'replyRequested' => 'bool',
        'createdAt' => '\DateTime',
        'from' => '\JTL\SCX\Lib\Channel\Client\Model\TicketFrom',
        'attachment' => '\JTL\SCX\Lib\Channel\Client\Model\TicketAttachment[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'sellerId' => null,
        'orderId' => null,
        'shippingComplete' => null,
        'shippingItems' => null,
        'paymentComplete' => null,
        'paidAt' => 'date-time',
        'offerId' => 'int64',
        'channelOfferId' => null,
        'parentOfferId' => 'int64',
        'channelCategoryId' => null,
        'quantity' => null,
        'taxPercent' => null,
        'priceList' => null,
        'title' => null,
        'subTitle' => null,
        'description' => null,
        'mainPicture' => null,
        'pictureList' => null,
        'channelAttributeList' => null,
        'variationList' => null,
        'sku' => null,
        'gtin' => null,
        'mpn' => null,
        'isbn' => null,
        'brand' => null,
        'srp' => null,
        'productAttributeList' => null,
        'channel' => null,
        'reportType' => null,
        'options' => null,
        'startDate' => 'date',
        'endDate' => 'date',
        'reportId' => null,
        'message' => null,
        'severity' => null,
        'reason' => null,
        'unlinkedAt' => 'date-time',
        'permanentlyRemoved' => null,
        'orderCancellationRequestId' => 'uuid',
        'orderItem' => null,
        'cancelReason' => null,
        'orderAccepted' => null,
        'type' => null,
        'invoiceNumber' => null,
        'documentId' => null,
        'documentExpiresAt' => 'date-time',
        'sellerReturnId' => null,
        'channelReturnId' => null,
        'refundId' => null,
        'ticketId' => null,
        'replyRequested' => null,
        'createdAt' => 'date-time',
        'from' => null,
        'attachment' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    protected static array $attributeMap = [
        'sellerId' => 'sellerId',
        'orderId' => 'orderId',
        'shippingComplete' => 'shippingComplete',
        'shippingItems' => 'shippingItems',
        'paymentComplete' => 'paymentComplete',
        'paidAt' => 'paidAt',
        'offerId' => 'offerId',
        'channelOfferId' => 'channelOfferId',
        'parentOfferId' => 'parentOfferId',
        'channelCategoryId' => 'channelCategoryId',
        'quantity' => 'quantity',
        'taxPercent' => 'taxPercent',
        'priceList' => 'priceList',
        'title' => 'title',
        'subTitle' => 'subTitle',
        'description' => 'description',
        'mainPicture' => 'mainPicture',
        'pictureList' => 'pictureList',
        'channelAttributeList' => 'channelAttributeList',
        'variationList' => 'variationList',
        'sku' => 'sku',
        'gtin' => 'gtin',
        'mpn' => 'mpn',
        'isbn' => 'isbn',
        'brand' => 'brand',
        'srp' => 'srp',
        'productAttributeList' => 'productAttributeList',
        'channel' => 'channel',
        'reportType' => 'reportType',
        'options' => 'options',
        'startDate' => 'startDate',
        'endDate' => 'endDate',
        'reportId' => 'reportId',
        'message' => 'message',
        'severity' => 'severity',
        'reason' => 'reason',
        'unlinkedAt' => 'unlinkedAt',
        'permanentlyRemoved' => 'permanentlyRemoved',
        'orderCancellationRequestId' => 'orderCancellationRequestId',
        'orderItem' => 'orderItem',
        'cancelReason' => 'cancelReason',
        'orderAccepted' => 'orderAccepted',
        'type' => 'type',
        'invoiceNumber' => 'invoiceNumber',
        'documentId' => 'documentId',
        'documentExpiresAt' => 'documentExpiresAt',
        'sellerReturnId' => 'sellerReturnId',
        'channelReturnId' => 'channelReturnId',
        'refundId' => 'refundId',
        'ticketId' => 'ticketId',
        'replyRequested' => 'replyRequested',
        'createdAt' => 'createdAt',
        'from' => 'from',
        'attachment' => 'attachment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    protected static array $setters = [
        'sellerId' => 'setSellerId',
        'orderId' => 'setOrderId',
        'shippingComplete' => 'setShippingComplete',
        'shippingItems' => 'setShippingItems',
        'paymentComplete' => 'setPaymentComplete',
        'paidAt' => 'setPaidAt',
        'offerId' => 'setOfferId',
        'channelOfferId' => 'setChannelOfferId',
        'parentOfferId' => 'setParentOfferId',
        'channelCategoryId' => 'setChannelCategoryId',
        'quantity' => 'setQuantity',
        'taxPercent' => 'setTaxPercent',
        'priceList' => 'setPriceList',
        'title' => 'setTitle',
        'subTitle' => 'setSubTitle',
        'description' => 'setDescription',
        'mainPicture' => 'setMainPicture',
        'pictureList' => 'setPictureList',
        'channelAttributeList' => 'setChannelAttributeList',
        'variationList' => 'setVariationList',
        'sku' => 'setSku',
        'gtin' => 'setGtin',
        'mpn' => 'setMpn',
        'isbn' => 'setIsbn',
        'brand' => 'setBrand',
        'srp' => 'setSrp',
        'productAttributeList' => 'setProductAttributeList',
        'channel' => 'setChannel',
        'reportType' => 'setReportType',
        'options' => 'setOptions',
        'startDate' => 'setStartDate',
        'endDate' => 'setEndDate',
        'reportId' => 'setReportId',
        'message' => 'setMessage',
        'severity' => 'setSeverity',
        'reason' => 'setReason',
        'unlinkedAt' => 'setUnlinkedAt',
        'permanentlyRemoved' => 'setPermanentlyRemoved',
        'orderCancellationRequestId' => 'setOrderCancellationRequestId',
        'orderItem' => 'setOrderItem',
        'cancelReason' => 'setCancelReason',
        'orderAccepted' => 'setOrderAccepted',
        'type' => 'setType',
        'invoiceNumber' => 'setInvoiceNumber',
        'documentId' => 'setDocumentId',
        'documentExpiresAt' => 'setDocumentExpiresAt',
        'sellerReturnId' => 'setSellerReturnId',
        'channelReturnId' => 'setChannelReturnId',
        'refundId' => 'setRefundId',
        'ticketId' => 'setTicketId',
        'replyRequested' => 'setReplyRequested',
        'createdAt' => 'setCreatedAt',
        'from' => 'setFrom',
        'attachment' => 'setAttachment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    protected static array $getters = [
        'sellerId' => 'getSellerId',
        'orderId' => 'getOrderId',
        'shippingComplete' => 'getShippingComplete',
        'shippingItems' => 'getShippingItems',
        'paymentComplete' => 'getPaymentComplete',
        'paidAt' => 'getPaidAt',
        'offerId' => 'getOfferId',
        'channelOfferId' => 'getChannelOfferId',
        'parentOfferId' => 'getParentOfferId',
        'channelCategoryId' => 'getChannelCategoryId',
        'quantity' => 'getQuantity',
        'taxPercent' => 'getTaxPercent',
        'priceList' => 'getPriceList',
        'title' => 'getTitle',
        'subTitle' => 'getSubTitle',
        'description' => 'getDescription',
        'mainPicture' => 'getMainPicture',
        'pictureList' => 'getPictureList',
        'channelAttributeList' => 'getChannelAttributeList',
        'variationList' => 'getVariationList',
        'sku' => 'getSku',
        'gtin' => 'getGtin',
        'mpn' => 'getMpn',
        'isbn' => 'getIsbn',
        'brand' => 'getBrand',
        'srp' => 'getSrp',
        'productAttributeList' => 'getProductAttributeList',
        'channel' => 'getChannel',
        'reportType' => 'getReportType',
        'options' => 'getOptions',
        'startDate' => 'getStartDate',
        'endDate' => 'getEndDate',
        'reportId' => 'getReportId',
        'message' => 'getMessage',
        'severity' => 'getSeverity',
        'reason' => 'getReason',
        'unlinkedAt' => 'getUnlinkedAt',
        'permanentlyRemoved' => 'getPermanentlyRemoved',
        'orderCancellationRequestId' => 'getOrderCancellationRequestId',
        'orderItem' => 'getOrderItem',
        'cancelReason' => 'getCancelReason',
        'orderAccepted' => 'getOrderAccepted',
        'type' => 'getType',
        'invoiceNumber' => 'getInvoiceNumber',
        'documentId' => 'getDocumentId',
        'documentExpiresAt' => 'getDocumentExpiresAt',
        'sellerReturnId' => 'getSellerReturnId',
        'channelReturnId' => 'getChannelReturnId',
        'refundId' => 'getRefundId',
        'ticketId' => 'getTicketId',
        'replyRequested' => 'getReplyRequested',
        'createdAt' => 'getCreatedAt',
        'from' => 'getFrom',
        'attachment' => 'getAttachment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     * @codeCoverageIgnore
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @codeCoverageIgnore
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @codeCoverageIgnore
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     * @codeCoverageIgnore
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const SEVERITY_INFO = 'INFO';
    public const SEVERITY_WARNING = 'WARNING';
    public const SEVERITY_ERROR = 'ERROR';



    /**
     * Gets allowable values of the enum
     */
    public function getSeverityAllowableValues(): array
    {
        return [
            self::SEVERITY_INFO,
            self::SEVERITY_WARNING,
            self::SEVERITY_ERROR,
        ];
    }


    /**
     * Associative array for storing property values
     */
    protected array $container = [];

    public function __construct(array|null $data = null)
    {
        $this->container['sellerId'] = $data['sellerId'] ?? null;
        $this->container['orderId'] = $data['orderId'] ?? null;
        $this->container['shippingComplete'] = $data['shippingComplete'] ?? null;
        $this->container['shippingItems'] = $data['shippingItems'] ?? null;
        $this->container['paymentComplete'] = $data['paymentComplete'] ?? null;
        $this->container['paidAt'] = $data['paidAt'] ?? null;
        $this->container['offerId'] = $data['offerId'] ?? null;
        $this->container['channelOfferId'] = $data['channelOfferId'] ?? null;
        $this->container['parentOfferId'] = $data['parentOfferId'] ?? null;
        $this->container['channelCategoryId'] = $data['channelCategoryId'] ?? null;
        $this->container['quantity'] = $data['quantity'] ?? null;
        $this->container['taxPercent'] = $data['taxPercent'] ?? null;
        $this->container['priceList'] = $data['priceList'] ?? null;
        $this->container['title'] = $data['title'] ?? null;
        $this->container['subTitle'] = $data['subTitle'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['mainPicture'] = $data['mainPicture'] ?? null;
        $this->container['pictureList'] = $data['pictureList'] ?? null;
        $this->container['channelAttributeList'] = $data['channelAttributeList'] ?? null;
        $this->container['variationList'] = $data['variationList'] ?? null;
        $this->container['sku'] = $data['sku'] ?? null;
        $this->container['gtin'] = $data['gtin'] ?? null;
        $this->container['mpn'] = $data['mpn'] ?? null;
        $this->container['isbn'] = $data['isbn'] ?? null;
        $this->container['brand'] = $data['brand'] ?? null;
        $this->container['srp'] = $data['srp'] ?? null;
        $this->container['productAttributeList'] = $data['productAttributeList'] ?? null;
        $this->container['channel'] = $data['channel'] ?? null;
        $this->container['reportType'] = $data['reportType'] ?? null;
        $this->container['options'] = $data['options'] ?? null;
        $this->container['startDate'] = $data['startDate'] ?? null;
        $this->container['endDate'] = $data['endDate'] ?? null;
        $this->container['reportId'] = $data['reportId'] ?? null;
        $this->container['message'] = $data['message'] ?? null;
        $this->container['severity'] = $data['severity'] ?? null;
        $this->container['reason'] = $data['reason'] ?? null;
        $this->container['unlinkedAt'] = $data['unlinkedAt'] ?? null;
        $this->container['permanentlyRemoved'] = $data['permanentlyRemoved'] ?? false;
        $this->container['orderCancellationRequestId'] = $data['orderCancellationRequestId'] ?? null;
        $this->container['orderItem'] = $data['orderItem'] ?? null;
        $this->container['cancelReason'] = $data['cancelReason'] ?? null;
        $this->container['orderAccepted'] = $data['orderAccepted'] ?? null;
        $this->container['type'] = $data['type'] ?? null;
        $this->container['invoiceNumber'] = $data['invoiceNumber'] ?? null;
        $this->container['documentId'] = $data['documentId'] ?? null;
        $this->container['documentExpiresAt'] = $data['documentExpiresAt'] ?? null;
        $this->container['sellerReturnId'] = $data['sellerReturnId'] ?? null;
        $this->container['channelReturnId'] = $data['channelReturnId'] ?? null;
        $this->container['refundId'] = $data['refundId'] ?? null;
        $this->container['ticketId'] = $data['ticketId'] ?? null;
        $this->container['replyRequested'] = $data['replyRequested'] ?? true;
        $this->container['createdAt'] = $data['createdAt'] ?? null;
        $this->container['from'] = $data['from'] ?? null;
        $this->container['attachment'] = $data['attachment'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     * @codeCoverageIgnore
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['sellerId'] === null) {
            $invalidProperties[] = "'sellerId' can't be null";
        }
        if (!preg_match("/^\\w{1,50}$/", $this->container['sellerId'])) {
            $invalidProperties[] = "invalid value for 'sellerId', must be conform to the pattern /^\\w{1,50}$/.";
        }

        if ($this->container['orderId'] === null) {
            $invalidProperties[] = "'orderId' can't be null";
        }
        if ((mb_strlen($this->container['orderId']) > 150)) {
            $invalidProperties[] = "invalid value for 'orderId', the character length must be smaller than or equal to 150.";
        }

        if ((mb_strlen($this->container['orderId']) < 1)) {
            $invalidProperties[] = "invalid value for 'orderId', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['shippingComplete'] === null) {
            $invalidProperties[] = "'shippingComplete' can't be null";
        }
        if ($this->container['shippingItems'] === null) {
            $invalidProperties[] = "'shippingItems' can't be null";
        }
        if ((is_countable($this->container['shippingItems']) && count($this->container['shippingItems']) < 1)) {
            $invalidProperties[] = "invalid value for 'shippingItems', number of items must be greater than or equal to 1.";
        }

        if ($this->container['paymentComplete'] === null) {
            $invalidProperties[] = "'paymentComplete' can't be null";
        }
        if ($this->container['paidAt'] === null) {
            $invalidProperties[] = "'paidAt' can't be null";
        }
        if ($this->container['offerId'] === null) {
            $invalidProperties[] = "'offerId' can't be null";
        }
        if (($this->container['offerId'] < 1)) {
            $invalidProperties[] = "invalid value for 'offerId', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['channelOfferId']) && (mb_strlen($this->container['channelOfferId']) > 100)) {
            $invalidProperties[] = "invalid value for 'channelOfferId', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['channelOfferId']) && (mb_strlen($this->container['channelOfferId']) < 1)) {
            $invalidProperties[] = "invalid value for 'channelOfferId', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['parentOfferId']) && ($this->container['parentOfferId'] < 1)) {
            $invalidProperties[] = "invalid value for 'parentOfferId', must be bigger than or equal to 1.";
        }

        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ($this->container['priceList'] === null) {
            $invalidProperties[] = "'priceList' can't be null";
        }
        if (!is_null($this->container['title']) && (mb_strlen($this->container['title']) > 512)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['title']) && (mb_strlen($this->container['title']) < 1)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['subTitle']) && (mb_strlen($this->container['subTitle']) > 1024)) {
            $invalidProperties[] = "invalid value for 'subTitle', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 50000)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 50000.";
        }

        if (!is_null($this->container['pictureList']) && (is_countable($this->container['pictureList']) && ($this->container['pictureList']) > 50)) {
            $invalidProperties[] = "invalid value for 'pictureList', number of items must be less than or equal to 50.";
        }

        if (!is_null($this->container['channelAttributeList']) && (is_countable($this->container['channelAttributeList']) && ($this->container['channelAttributeList']) > 250)) {
            $invalidProperties[] = "invalid value for 'channelAttributeList', number of items must be less than or equal to 250.";
        }

        if (!is_null($this->container['channelAttributeList']) && (is_countable($this->container['channelAttributeList']) && count($this->container['channelAttributeList']) < 0)) {
            $invalidProperties[] = "invalid value for 'channelAttributeList', number of items must be greater than or equal to 0.";
        }

        if (!is_null($this->container['variationList']) && (is_countable($this->container['variationList']) && ($this->container['variationList']) > 500)) {
            $invalidProperties[] = "invalid value for 'variationList', number of items must be less than or equal to 500.";
        }

        if (!is_null($this->container['variationList']) && (is_countable($this->container['variationList']) && count($this->container['variationList']) < 0)) {
            $invalidProperties[] = "invalid value for 'variationList', number of items must be greater than or equal to 0.";
        }

        if ($this->container['sku'] === null) {
            $invalidProperties[] = "'sku' can't be null";
        }
        if ((mb_strlen($this->container['sku']) > 150)) {
            $invalidProperties[] = "invalid value for 'sku', the character length must be smaller than or equal to 150.";
        }

        if ((mb_strlen($this->container['sku']) < 1)) {
            $invalidProperties[] = "invalid value for 'sku', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['channel'] === null) {
            $invalidProperties[] = "'channel' can't be null";
        }
        if (!preg_match("/^\\w{5,15}$/", $this->container['channel'])) {
            $invalidProperties[] = "invalid value for 'channel', must be conform to the pattern /^\\w{5,15}$/.";
        }

        if ($this->container['reportType'] === null) {
            $invalidProperties[] = "'reportType' can't be null";
        }
        if ($this->container['reportId'] === null) {
            $invalidProperties[] = "'reportId' can't be null";
        }
        if ($this->container['message'] === null) {
            $invalidProperties[] = "'message' can't be null";
        }
        if ((mb_strlen($this->container['message']) > 1024)) {
            $invalidProperties[] = "invalid value for 'message', the character length must be smaller than or equal to 1024.";
        }

        if ((mb_strlen($this->container['message']) < 1)) {
            $invalidProperties[] = "invalid value for 'message', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['severity'] === null) {
            $invalidProperties[] = "'severity' can't be null";
        }
        $allowedValues = $this->getSeverityAllowableValues();
        if (!is_null($this->container['severity']) && !in_array($this->container['severity'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'severity', must be one of '%s'",
                $this->container['severity'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['reason'] === null) {
            $invalidProperties[] = "'reason' can't be null";
        }
        if ($this->container['unlinkedAt'] === null) {
            $invalidProperties[] = "'unlinkedAt' can't be null";
        }
        if ($this->container['orderCancellationRequestId'] === null) {
            $invalidProperties[] = "'orderCancellationRequestId' can't be null";
        }
        if ($this->container['orderItem'] === null) {
            $invalidProperties[] = "'orderItem' can't be null";
        }
        if ((is_countable($this->container['orderItem']) && count($this->container['orderItem']) < 1)) {
            $invalidProperties[] = "invalid value for 'orderItem', number of items must be greater than or equal to 1.";
        }

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['invoiceNumber'] === null) {
            $invalidProperties[] = "'invoiceNumber' can't be null";
        }
        if ((mb_strlen($this->container['invoiceNumber']) > 256)) {
            $invalidProperties[] = "invalid value for 'invoiceNumber', the character length must be smaller than or equal to 256.";
        }

        if ((mb_strlen($this->container['invoiceNumber']) < 1)) {
            $invalidProperties[] = "invalid value for 'invoiceNumber', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['documentId'] === null) {
            $invalidProperties[] = "'documentId' can't be null";
        }
        if ($this->container['documentExpiresAt'] === null) {
            $invalidProperties[] = "'documentExpiresAt' can't be null";
        }
        if ($this->container['sellerReturnId'] === null) {
            $invalidProperties[] = "'sellerReturnId' can't be null";
        }
        if ($this->container['refundId'] === null) {
            $invalidProperties[] = "'refundId' can't be null";
        }
        if ((mb_strlen($this->container['refundId']) > 128)) {
            $invalidProperties[] = "invalid value for 'refundId', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['refundId']) < 1)) {
            $invalidProperties[] = "invalid value for 'refundId', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['ticketId'] === null) {
            $invalidProperties[] = "'ticketId' can't be null";
        }
        if ((mb_strlen($this->container['ticketId']) > 256)) {
            $invalidProperties[] = "invalid value for 'ticketId', the character length must be smaller than or equal to 256.";
        }

        if ((mb_strlen($this->container['ticketId']) < 1)) {
            $invalidProperties[] = "invalid value for 'ticketId', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if (!is_null($this->container['attachment']) && (is_countable($this->container['attachment']) && ($this->container['attachment']) > 10)) {
            $invalidProperties[] = "invalid value for 'attachment', number of items must be less than or equal to 10.";
        }

        if (!is_null($this->container['attachment']) && (is_countable($this->container['attachment']) && count($this->container['attachment']) < 0)) {
            $invalidProperties[] = "invalid value for 'attachment', number of items must be greater than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     * @codeCoverageIgnore
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    public function getSellerId(): string
    {
        return $this->container['sellerId'];
    }

    public function setSellerId(string $sellerId): SellerEventListEventListInnerEvent
    {
        $this->container['sellerId'] = $sellerId;
        return $this;
    }


    public function getOrderId(): string
    {
        return $this->container['orderId'];
    }

    public function setOrderId(string $orderId): SellerEventListEventListInnerEvent
    {
        $this->container['orderId'] = $orderId;
        return $this;
    }


    public function getShippingComplete(): bool
    {
        return $this->container['shippingComplete'];
    }

    public function setShippingComplete(bool $shippingComplete): SellerEventListEventListInnerEvent
    {
        $this->container['shippingComplete'] = $shippingComplete;
        return $this;
    }


    public function getShippingItems(): array
    {
        return $this->container['shippingItems'];
    }

    public function setShippingItems(array $shippingItems): SellerEventListEventListInnerEvent
    {
        $this->container['shippingItems'] = $shippingItems;
        return $this;
    }


    public function getPaymentComplete(): bool
    {
        return $this->container['paymentComplete'];
    }

    public function setPaymentComplete(bool $paymentComplete): SellerEventListEventListInnerEvent
    {
        $this->container['paymentComplete'] = $paymentComplete;
        return $this;
    }


    public function getPaidAt(): \DateTime
    {
        return $this->container['paidAt'];
    }

    public function setPaidAt(\DateTime $paidAt): SellerEventListEventListInnerEvent
    {
        $this->container['paidAt'] = $paidAt;
        return $this;
    }


    public function getOfferId(): int
    {
        return $this->container['offerId'];
    }

    public function setOfferId(int $offerId): SellerEventListEventListInnerEvent
    {
        $this->container['offerId'] = $offerId;
        return $this;
    }


    public function getChannelOfferId(): ?string
    {
        return $this->container['channelOfferId'];
    }

    public function setChannelOfferId(?string $channelOfferId): SellerEventListEventListInnerEvent
    {
        $this->container['channelOfferId'] = $channelOfferId;
        return $this;
    }


    public function getParentOfferId(): ?int
    {
        return $this->container['parentOfferId'];
    }

    public function setParentOfferId(?int $parentOfferId): SellerEventListEventListInnerEvent
    {
        $this->container['parentOfferId'] = $parentOfferId;
        return $this;
    }


    public function getChannelCategoryId(): ?string
    {
        return $this->container['channelCategoryId'];
    }

    public function setChannelCategoryId(?string $channelCategoryId): SellerEventListEventListInnerEvent
    {
        $this->container['channelCategoryId'] = $channelCategoryId;
        return $this;
    }


    public function getQuantity(): string
    {
        return $this->container['quantity'];
    }

    public function setQuantity(string $quantity): SellerEventListEventListInnerEvent
    {
        $this->container['quantity'] = $quantity;
        return $this;
    }


    public function getTaxPercent(): ?string
    {
        return $this->container['taxPercent'];
    }

    public function setTaxPercent(?string $taxPercent): SellerEventListEventListInnerEvent
    {
        $this->container['taxPercent'] = $taxPercent;
        return $this;
    }


    public function getPriceList(): array
    {
        return $this->container['priceList'];
    }

    public function setPriceList(array $priceList): SellerEventListEventListInnerEvent
    {
        $this->container['priceList'] = $priceList;
        return $this;
    }


    public function getTitle(): ?string
    {
        return $this->container['title'];
    }

    public function setTitle(?string $title): SellerEventListEventListInnerEvent
    {
        $this->container['title'] = $title;
        return $this;
    }


    public function getSubTitle(): ?string
    {
        return $this->container['subTitle'];
    }

    public function setSubTitle(?string $subTitle): SellerEventListEventListInnerEvent
    {
        $this->container['subTitle'] = $subTitle;
        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    public function setDescription(?string $description): SellerEventListEventListInnerEvent
    {
        $this->container['description'] = $description;
        return $this;
    }


    public function getMainPicture(): ?string
    {
        return $this->container['mainPicture'];
    }

    public function setMainPicture(?string $mainPicture): SellerEventListEventListInnerEvent
    {
        $this->container['mainPicture'] = $mainPicture;
        return $this;
    }


    public function getPictureList(): ?array
    {
        return $this->container['pictureList'];
    }

    public function setPictureList(?array $pictureList): SellerEventListEventListInnerEvent
    {
        $this->container['pictureList'] = $pictureList;
        return $this;
    }


    public function getChannelAttributeList(): ?array
    {
        return $this->container['channelAttributeList'];
    }

    public function setChannelAttributeList(?array $channelAttributeList): SellerEventListEventListInnerEvent
    {
        $this->container['channelAttributeList'] = $channelAttributeList;
        return $this;
    }


    public function getVariationList(): ?array
    {
        return $this->container['variationList'];
    }

    public function setVariationList(?array $variationList): SellerEventListEventListInnerEvent
    {
        $this->container['variationList'] = $variationList;
        return $this;
    }


    public function getSku(): string
    {
        return $this->container['sku'];
    }

    public function setSku(string $sku): SellerEventListEventListInnerEvent
    {
        $this->container['sku'] = $sku;
        return $this;
    }


    public function getGtin(): ?string
    {
        return $this->container['gtin'];
    }

    public function setGtin(?string $gtin): SellerEventListEventListInnerEvent
    {
        $this->container['gtin'] = $gtin;
        return $this;
    }


    public function getMpn(): ?string
    {
        return $this->container['mpn'];
    }

    public function setMpn(?string $mpn): SellerEventListEventListInnerEvent
    {
        $this->container['mpn'] = $mpn;
        return $this;
    }


    public function getIsbn(): ?string
    {
        return $this->container['isbn'];
    }

    public function setIsbn(?string $isbn): SellerEventListEventListInnerEvent
    {
        $this->container['isbn'] = $isbn;
        return $this;
    }


    public function getBrand(): ?string
    {
        return $this->container['brand'];
    }

    public function setBrand(?string $brand): SellerEventListEventListInnerEvent
    {
        $this->container['brand'] = $brand;
        return $this;
    }


    public function getSrp(): ?Price
    {
        return $this->container['srp'];
    }

    public function setSrp(?Price $srp): SellerEventListEventListInnerEvent
    {
        $this->container['srp'] = $srp;
        return $this;
    }


    public function getProductAttributeList(): ?array
    {
        return $this->container['productAttributeList'];
    }

    public function setProductAttributeList(?array $productAttributeList): SellerEventListEventListInnerEvent
    {
        $this->container['productAttributeList'] = $productAttributeList;
        return $this;
    }


    public function getChannel(): string
    {
        return $this->container['channel'];
    }

    public function setChannel(string $channel): SellerEventListEventListInnerEvent
    {
        $this->container['channel'] = $channel;
        return $this;
    }


    public function getReportType(): ReportType
    {
        return $this->container['reportType'];
    }

    public function setReportType(ReportType $reportType): SellerEventListEventListInnerEvent
    {
        $this->container['reportType'] = $reportType;
        return $this;
    }


    public function getOptions(): ?ReportRequestOptions
    {
        return $this->container['options'];
    }

    public function setOptions(?ReportRequestOptions $options): SellerEventListEventListInnerEvent
    {
        $this->container['options'] = $options;
        return $this;
    }


    public function getStartDate(): ?\DateTime
    {
        return $this->container['startDate'];
    }

    public function setStartDate(?\DateTime $startDate): SellerEventListEventListInnerEvent
    {
        $this->container['startDate'] = $startDate;
        return $this;
    }


    public function getEndDate(): ?\DateTime
    {
        return $this->container['endDate'];
    }

    public function setEndDate(?\DateTime $endDate): SellerEventListEventListInnerEvent
    {
        $this->container['endDate'] = $endDate;
        return $this;
    }


    public function getReportId(): string
    {
        return $this->container['reportId'];
    }

    public function setReportId(string $reportId): SellerEventListEventListInnerEvent
    {
        $this->container['reportId'] = $reportId;
        return $this;
    }


    public function getMessage(): string
    {
        return $this->container['message'];
    }

    public function setMessage(string $message): SellerEventListEventListInnerEvent
    {
        $this->container['message'] = $message;
        return $this;
    }


    public function getSeverity(): string
    {
        return $this->container['severity'];
    }

    public function setSeverity(string $severity): SellerEventListEventListInnerEvent
    {
        $this->container['severity'] = $severity;
        return $this;
    }


    public function getReason(): CancelReason
    {
        return $this->container['reason'];
    }

    public function setReason(CancelReason $reason): SellerEventListEventListInnerEvent
    {
        $this->container['reason'] = $reason;
        return $this;
    }


    public function getUnlinkedAt(): \DateTime
    {
        return $this->container['unlinkedAt'];
    }

    public function setUnlinkedAt(\DateTime $unlinkedAt): SellerEventListEventListInnerEvent
    {
        $this->container['unlinkedAt'] = $unlinkedAt;
        return $this;
    }


    public function getPermanentlyRemoved(): ?bool
    {
        return $this->container['permanentlyRemoved'];
    }

    public function setPermanentlyRemoved(?bool $permanentlyRemoved): SellerEventListEventListInnerEvent
    {
        $this->container['permanentlyRemoved'] = $permanentlyRemoved;
        return $this;
    }


    public function getOrderCancellationRequestId(): string
    {
        return $this->container['orderCancellationRequestId'];
    }

    public function setOrderCancellationRequestId(string $orderCancellationRequestId): SellerEventListEventListInnerEvent
    {
        $this->container['orderCancellationRequestId'] = $orderCancellationRequestId;
        return $this;
    }


    public function getOrderItem(): array
    {
        return $this->container['orderItem'];
    }

    public function setOrderItem(array $orderItem): SellerEventListEventListInnerEvent
    {
        $this->container['orderItem'] = $orderItem;
        return $this;
    }


    public function getCancelReason(): ?CancelReason
    {
        return $this->container['cancelReason'];
    }

    public function setCancelReason(?CancelReason $cancelReason): SellerEventListEventListInnerEvent
    {
        $this->container['cancelReason'] = $cancelReason;
        return $this;
    }


    public function getOrderAccepted(): ?bool
    {
        return $this->container['orderAccepted'];
    }

    public function setOrderAccepted(?bool $orderAccepted): SellerEventListEventListInnerEvent
    {
        $this->container['orderAccepted'] = $orderAccepted;
        return $this;
    }


    public function getType(): InvoiceDocumentType
    {
        return $this->container['type'];
    }

    public function setType(InvoiceDocumentType $type): SellerEventListEventListInnerEvent
    {
        $this->container['type'] = $type;
        return $this;
    }


    public function getInvoiceNumber(): string
    {
        return $this->container['invoiceNumber'];
    }

    public function setInvoiceNumber(string $invoiceNumber): SellerEventListEventListInnerEvent
    {
        $this->container['invoiceNumber'] = $invoiceNumber;
        return $this;
    }


    public function getDocumentId(): string
    {
        return $this->container['documentId'];
    }

    public function setDocumentId(string $documentId): SellerEventListEventListInnerEvent
    {
        $this->container['documentId'] = $documentId;
        return $this;
    }


    public function getDocumentExpiresAt(): \DateTime
    {
        return $this->container['documentExpiresAt'];
    }

    public function setDocumentExpiresAt(\DateTime $documentExpiresAt): SellerEventListEventListInnerEvent
    {
        $this->container['documentExpiresAt'] = $documentExpiresAt;
        return $this;
    }


    public function getSellerReturnId(): string
    {
        return $this->container['sellerReturnId'];
    }

    public function setSellerReturnId(string $sellerReturnId): SellerEventListEventListInnerEvent
    {
        $this->container['sellerReturnId'] = $sellerReturnId;
        return $this;
    }


    public function getChannelReturnId(): ?string
    {
        return $this->container['channelReturnId'];
    }

    public function setChannelReturnId(?string $channelReturnId): SellerEventListEventListInnerEvent
    {
        $this->container['channelReturnId'] = $channelReturnId;
        return $this;
    }


    public function getRefundId(): string
    {
        return $this->container['refundId'];
    }

    public function setRefundId(string $refundId): SellerEventListEventListInnerEvent
    {
        $this->container['refundId'] = $refundId;
        return $this;
    }


    public function getTicketId(): string
    {
        return $this->container['ticketId'];
    }

    public function setTicketId(string $ticketId): SellerEventListEventListInnerEvent
    {
        $this->container['ticketId'] = $ticketId;
        return $this;
    }


    public function getReplyRequested(): ?bool
    {
        return $this->container['replyRequested'];
    }

    public function setReplyRequested(?bool $replyRequested): SellerEventListEventListInnerEvent
    {
        $this->container['replyRequested'] = $replyRequested;
        return $this;
    }


    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    public function setCreatedAt(\DateTime $createdAt): SellerEventListEventListInnerEvent
    {
        $this->container['createdAt'] = $createdAt;
        return $this;
    }


    public function getFrom(): TicketFrom
    {
        return $this->container['from'];
    }

    public function setFrom(TicketFrom $from): SellerEventListEventListInnerEvent
    {
        $this->container['from'] = $from;
        return $this;
    }


    public function getAttachment(): ?array
    {
        return $this->container['attachment'];
    }

    public function setAttachment(?array $attachment): SellerEventListEventListInnerEvent
    {
        $this->container['attachment'] = $attachment;
        return $this;
    }

    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     */
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     * @codeCoverageIgnore
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     * @codeCoverageIgnore
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     * @codeCoverageIgnore
     */
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     * @codeCoverageIgnore
     */
    public function __toString(): string
    {
        return json_encode(
            $this->jsonSerialize(),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     * @codeCoverageIgnore
     */
    public function toHeaderValue(): string
    {
        return json_encode($this->jsonSerialize());
    }
}
