<?php
/**
 * SellerEventTypeList
 *
 * PHP version 8.4
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\EnumInterface;

/**
 * SellerEventTypeList Class Doc Comment
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SellerEventTypeList implements EnumInterface
{
    private $value;

    /**
     * Possible values of this enum
     */
    public const SYSTEM_TEST = 'System:Test';
    public const SYSTEM_NOTIFICATION = 'System:Notification';
    public const SELLER_ORDER_CONFIRMED = 'Seller:Order.Confirmed';
    public const SELLER_ORDER_SHIPPING = 'Seller:Order.Shipping';
    public const SELLER_ORDER_PAYMENT = 'Seller:Order.Payment';
    public const SELLER_ORDER_CANCELLATION_REQUEST = 'Seller:Order.Cancellation.Request';
    public const SELLER_ORDER_CANCELLATION_ACCEPTED = 'Seller:Order.Cancellation.Accepted';
    public const SELLER_ORDER_CANCELLATION_DENIED = 'Seller:Order.Cancellation.Denied';
    public const SELLER_ORDER_REFUND = 'Seller:Order.Refund';
    public const SELLER_ORDER_INVOICE = 'Seller:Order.Invoice';
    public const SELLER_ORDER_RETURN_RECEIVED = 'Seller:Order.ReturnReceived';
    public const SELLER_OFFER_NEW = 'Seller:Offer.New';
    public const SELLER_OFFER_UPDATE = 'Seller:Offer.Update';
    public const SELLER_OFFER_END = 'Seller:Offer.End';
    public const SELLER_OFFER_STOCK_UPDATE = 'Seller:Offer.StockUpdate';
    public const SELLER_OFFER_PRICE_UPDATE = 'Seller:Offer.PriceUpdate';
    public const SELLER_REPORT_REQUEST = 'Seller:Report.Request';
    public const SELLER_CHANNEL_UNLINKED = 'Seller:Channel.Unlinked';
    public const SELLER_META_SELLER_ATTRIBUTES_UPDATE_REQUEST = 'Seller:Meta.SellerAttributesUpdateRequest';
    public const SELLER_TICKET_REPLY = 'Seller:Ticket.Reply';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SYSTEM_TEST,
            self::SYSTEM_NOTIFICATION,
            self::SELLER_ORDER_CONFIRMED,
            self::SELLER_ORDER_SHIPPING,
            self::SELLER_ORDER_PAYMENT,
            self::SELLER_ORDER_CANCELLATION_REQUEST,
            self::SELLER_ORDER_CANCELLATION_ACCEPTED,
            self::SELLER_ORDER_CANCELLATION_DENIED,
            self::SELLER_ORDER_REFUND,
            self::SELLER_ORDER_INVOICE,
            self::SELLER_ORDER_RETURN_RECEIVED,
            self::SELLER_OFFER_NEW,
            self::SELLER_OFFER_UPDATE,
            self::SELLER_OFFER_END,
            self::SELLER_OFFER_STOCK_UPDATE,
            self::SELLER_OFFER_PRICE_UPDATE,
            self::SELLER_REPORT_REQUEST,
            self::SELLER_CHANNEL_UNLINKED,
            self::SELLER_META_SELLER_ATTRIBUTES_UPDATE_REQUEST,
            self::SELLER_TICKET_REPLY,
        ];
    }


    public static function SYSTEM_TEST(): SellerEventTypeList
    {
        return new self('System:Test');
    }

    public static function SYSTEM_NOTIFICATION(): SellerEventTypeList
    {
        return new self('System:Notification');
    }

    public static function SELLER_ORDER_CONFIRMED(): SellerEventTypeList
    {
        return new self('Seller:Order.Confirmed');
    }

    public static function SELLER_ORDER_SHIPPING(): SellerEventTypeList
    {
        return new self('Seller:Order.Shipping');
    }

    public static function SELLER_ORDER_PAYMENT(): SellerEventTypeList
    {
        return new self('Seller:Order.Payment');
    }

    public static function SELLER_ORDER_CANCELLATION_REQUEST(): SellerEventTypeList
    {
        return new self('Seller:Order.Cancellation.Request');
    }

    public static function SELLER_ORDER_CANCELLATION_ACCEPTED(): SellerEventTypeList
    {
        return new self('Seller:Order.Cancellation.Accepted');
    }

    public static function SELLER_ORDER_CANCELLATION_DENIED(): SellerEventTypeList
    {
        return new self('Seller:Order.Cancellation.Denied');
    }

    public static function SELLER_ORDER_REFUND(): SellerEventTypeList
    {
        return new self('Seller:Order.Refund');
    }

    public static function SELLER_ORDER_INVOICE(): SellerEventTypeList
    {
        return new self('Seller:Order.Invoice');
    }

    public static function SELLER_ORDER_RETURN_RECEIVED(): SellerEventTypeList
    {
        return new self('Seller:Order.ReturnReceived');
    }

    public static function SELLER_OFFER_NEW(): SellerEventTypeList
    {
        return new self('Seller:Offer.New');
    }

    public static function SELLER_OFFER_UPDATE(): SellerEventTypeList
    {
        return new self('Seller:Offer.Update');
    }

    public static function SELLER_OFFER_END(): SellerEventTypeList
    {
        return new self('Seller:Offer.End');
    }

    public static function SELLER_OFFER_STOCK_UPDATE(): SellerEventTypeList
    {
        return new self('Seller:Offer.StockUpdate');
    }

    public static function SELLER_OFFER_PRICE_UPDATE(): SellerEventTypeList
    {
        return new self('Seller:Offer.PriceUpdate');
    }

    public static function SELLER_REPORT_REQUEST(): SellerEventTypeList
    {
        return new self('Seller:Report.Request');
    }

    public static function SELLER_CHANNEL_UNLINKED(): SellerEventTypeList
    {
        return new self('Seller:Channel.Unlinked');
    }

    public static function SELLER_META_SELLER_ATTRIBUTES_UPDATE_REQUEST(): SellerEventTypeList
    {
        return new self('Seller:Meta.SellerAttributesUpdateRequest');
    }

    public static function SELLER_TICKET_REPLY(): SellerEventTypeList
    {
        return new self('Seller:Ticket.Reply');
    }


    public function __construct($value)
    {
        $this->value = $value;
    }

    public function getValue()
    {
        return $this->value;
    }
}
