<?php
/**
 * ShippingRules
 *
 * PHP version 8.4
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use ArrayAccess;
use JTL\SCX\Lib\Channel\Client\ObjectSerializer;

/**
 * ShippingRules Class Doc Comment
 *
 * @category Class
 * @description Shipping rules supported by the channel — list of carriers and the regions they cover.
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ShippingRules implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      */
    protected static string $openAPIModelName = 'ShippingRules';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @param SupportedCarrier
      *
      */
    protected static array $openAPITypes = [
        'supportedCarrierList' => '\JTL\SCX\Lib\Channel\Client\Model\SupportedCarrier[]',
        'channelSpecificAttributeList' => '\JTL\SCX\Lib\Channel\Client\Model\ChannelSpecificShippingAttribute[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'supportedCarrierList' => null,
        'channelSpecificAttributeList' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     * @codeCoverageIgnore
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    protected static array $attributeMap = [
        'supportedCarrierList' => 'supportedCarrierList',
        'channelSpecificAttributeList' => 'channelSpecificAttributeList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    protected static array $setters = [
        'supportedCarrierList' => 'setSupportedCarrierList',
        'channelSpecificAttributeList' => 'setChannelSpecificAttributeList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    protected static array $getters = [
        'supportedCarrierList' => 'getSupportedCarrierList',
        'channelSpecificAttributeList' => 'getChannelSpecificAttributeList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     * @codeCoverageIgnore
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @codeCoverageIgnore
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @codeCoverageIgnore
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     * @codeCoverageIgnore
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }





    /**
     * Associative array for storing property values
     */
    protected array $container = [];

    public function __construct(array|null $data = null)
    {
        $this->container['supportedCarrierList'] = $data['supportedCarrierList'] ?? null;
        $this->container['channelSpecificAttributeList'] = $data['channelSpecificAttributeList'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     * @codeCoverageIgnore
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['supportedCarrierList']) && (is_countable($this->container['supportedCarrierList']) && count($this->container['supportedCarrierList']) < 0)) {
            $invalidProperties[] = "invalid value for 'supportedCarrierList', number of items must be greater than or equal to 0.";
        }

        if (!is_null($this->container['channelSpecificAttributeList']) && (is_countable($this->container['channelSpecificAttributeList']) && count($this->container['channelSpecificAttributeList']) > 8)) {
            $invalidProperties[] = "invalid value for 'channelSpecificAttributeList', number of items must be less than or equal to 8.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     * @codeCoverageIgnore
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    public function getSupportedCarrierList(): ?array
    {
        return $this->container['supportedCarrierList'];
    }

    public function setSupportedCarrierList(?array $supportedCarrierList): ShippingRules
    {
        $this->container['supportedCarrierList'] = $supportedCarrierList;
        return $this;
    }

    public function getChannelSpecificAttributeList(): ?array
    {
        return $this->container['channelSpecificAttributeList'];
    }

    public function setChannelSpecificAttributeList(?array $channelSpecificAttributeList): ShippingRules
    {
        $this->container['channelSpecificAttributeList'] = $channelSpecificAttributeList;
        return $this;
    }

    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     */
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     * @codeCoverageIgnore
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     * @codeCoverageIgnore
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     * @codeCoverageIgnore
     */
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     * @codeCoverageIgnore
     */
    public function __toString(): string
    {
        return json_encode(
            $this->jsonSerialize(),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     * @codeCoverageIgnore
     */
    public function toHeaderValue(): string
    {
        return json_encode($this->jsonSerialize());
    }
}
