<?php
/**
 * ShippingAttributeLevel
 *
 * PHP version 8.4
 *
 * @category Class
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace JTL\SCX\Lib\Channel\Client\Model;

use JTL\SCX\Lib\Channel\Client\EnumInterface;

/**
 * ShippingAttributeLevel Class Doc Comment
 *
 * @category Class
 * @description Defines on which entity a shipping attribute is captured.  * Level **ORDER_ITEM** the attribute value is captured per order item (e.g. &#x60;IMEI&#x60;, &#x60;SERIAL_NUMBER&#x60;). * Level **SHIPMENT** the attribute value is captured per shipment (e.g. &#x60;DELIVERY_NOTE_NUMBER&#x60;).
 * @package  JTL\SCX\Lib\Channel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingAttributeLevel implements EnumInterface
{
    private $value;

    /**
     * Possible values of this enum
     */
    public const ORDER_ITEM = 'ORDER_ITEM';
    public const SHIPMENT = 'SHIPMENT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ORDER_ITEM,
            self::SHIPMENT,
        ];
    }


    public static function ORDER_ITEM(): ShippingAttributeLevel
    {
        return new self('ORDER_ITEM');
    }

    public static function SHIPMENT(): ShippingAttributeLevel
    {
        return new self('SHIPMENT');
    }


    public function __construct($value)
    {
        $this->value = $value;
    }

    public function getValue()
    {
        return $this->value;
    }
}
